### ISSUE TITLE
-Wunused-function in drivers/soundwire/intel_init.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1006]
via kernelci:
```
    drivers/soundwire/intel_init.c:193:14: warning: unused function 'sdw_intel_init' [-Wunused-function]
```

**Comment by nathanchance** [comment]
Caused by https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=2978a43e7690edfc816f2002aacc1bb382f50f11.

Commented for now, I can send a patch later if need be but I am hoping the patch is dropped and required to be resubmitted: https://lore.kernel.org/lkml/20200423180323.GA18440@ubuntu-s3-xlarge-x86

**Comment by nathanchance** [comment]
Someone else sent a patch to fix this: https://lore.kernel.org/lkml/20200422190815.5975-1-sudipm.mukherjee@gmail.com/

**Comment by nathanchance** [comment]
The offending patch has been dropped.
