### ISSUE TITLE
-Wbraced-scalar-init in drivers/gpu/drm/omapdrm/omap_connector.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1059]
For some reason, this appears after https://git.kernel.org/next/linux-next/c/42acb06b01b12a2205757a46d3ff75e38840968f...

```
drivers/gpu/drm/omapdrm/omap_connector.c:92:39: warning: braces around scalar initializer [-Wbraced-scalar-init]
        struct drm_display_mode new_mode = { { 0 } };
                                             ^~~~~~
1 warning generated.
```

I guess this would be the proper fix?

```diff
diff --git a/drivers/gpu/drm/omapdrm/omap_connector.c b/drivers/gpu/drm/omapdrm/omap_connector.c
index 528764566b17..de95dc1b861c 100644
--- a/drivers/gpu/drm/omapdrm/omap_connector.c
+++ b/drivers/gpu/drm/omapdrm/omap_connector.c
@@ -89,7 +89,7 @@ static enum drm_mode_status omap_connector_mode_valid(struct drm_connector *conn
                                 struct drm_display_mode *mode)
 {
        struct omap_connector *omap_connector = to_omap_connector(connector);
-       struct drm_display_mode new_mode = { { 0 } };
+       struct drm_display_mode new_mode = {};
        enum drm_mode_status status;

        status = omap_connector_mode_fixup(omap_connector->output, mode,
```

Although I am not even sure this initialization is needed, the structure is only being passed by reference:

```
$ sed -n '88,110p' drivers/gpu/drm/omapdrm/omap_connector.c
static enum drm_mode_status omap_connector_mode_valid(struct drm_connector *connector,
                                 struct drm_display_mode *mode)
{
        struct omap_connector *omap_connector = to_omap_connector(connector);
        struct drm_display_mode new_mode = { { 0 } };
        enum drm_mode_status status;

        status = omap_connector_mode_fixup(omap_connector->output, mode,
                                           &new_mode);
        if (status != MODE_OK)
                goto done;

        /* Check if vrefresh is still valid. */
        if (drm_mode_vrefresh(mode) != drm_mode_vrefresh(&new_mode))
                status = MODE_NOCLOCK;

done:
        DBG("connector: mode %s: " DRM_MODE_FMT,
                        (status == MODE_OK) ? "valid" : "invalid",
                        DRM_MODE_ARG(mode));

        return status;
}
```

**Comment by nickdesaulniers** [comment]
The definition of `struct drm_display_mode` from include/drm/drm_modes.h starts with:
```c
 struct drm_display_mode {                                                                                                                                                                                                                                           
   /**                                                                                                                                                                                                                                                               
    * @head:                                                                                                                                                                                                                                                         
    *                                                                                                                                                                                                                                                                
    * struct list_head for mode lists.                                                                                                                                                                                                                               
    */                                                                                                                                                                                                                                                               
   struct list_head head;
```
So the aggregate initializer used to initialize an instance of `struct drm_display_mode` with the identifier `new_mode` is only initializing the first member (`struct list_head`) explicitly.

https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.cbclx01/designators.htm

has pretty good coverage of the rules for C (I think they're different for C++).

> Although I am not even sure this initialization is needed, the structure is only being passed by reference

That depends on whether `omap_connector_mode_fixup` initializes all members of the `struct drm_display_mode*` argument, or only the members used by later calls, or none.  Also, if that reference is passed around and stored globally (ie. it "escapes") then it might be used later and end up with a pointer to uninitialized memory.

`drm_mode_create` looks like such an initialization routine, though I'm not familiar with the DRM interfaces.  It looks like the `struct omap_encoder` has a member `base` (`struct drm_encoder`), which has a member `dev` (`struct drm_device*).  Though, `drm_mode_create` does dynamically allocate a `struct drm_device`, `struct drm_device` look quite big so I worry about stack allocating them in the first place.

It looks like `omap_connector_mode_fixup` calls `drm_mode_copy` to copy the 2rd argument to `omap_connector_mode_fixup` into the 3rd.  In that case, since the 2rd argument should be a properly intialized instance of a `struct drm_display_mode*`, then I think its safe to just skip initializing `new_mode` here.  All `omap_connector_mode_fixup` does is copy one `struct drm_display_mode` entirely over to another, overwriting just the `head` member.  Otherwise just use `memset`.

**Comment by nathanchance** [comment]
Patch sent: https://lore.kernel.org/lkml/20200623013610.555610-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Fixed in a different way: https://cgit.freedesktop.org/drm/drm-tip/commit/?id=7d98404c8162b7f1d1b22eccce92f5ee7f93cab8
