### ISSUE TITLE
[cross compiling] build with gnu asm fails

### ISSUE THREAD

**Issue by n8v8R** [ClangBuiltLinux/linux#1132]
trying to cross compile 5.9-rc1 on a linux x86_64 node (_llvm-10_ | _gcc 9.3.0_) with `ARCH=arm CROSS_COMPILE=armv7-linux-gnueabihf make -j8 LLVM=1` and this kconfig [.config.txt](https://github.com/ClangBuiltLinux/linux/files/5086763/default.config.txt)

produces:

```
  HOSTCC  scripts/mod/mk_elfconfig
  CC      scripts/mod/empty.o
  CC      scripts/mod/devicetable-offsets.s
/usr/bin/as: unrecognized option '-EL'
clang: error: assembler command failed with exit code 1 (use -v to see invocation)
make[1]: *** [scripts/Makefile.build:283: scripts/mod/empty.o] Error 1
```

**Comment by nathanchance** [comment]
This is due to the fact that your `CROSS_COMPILE` does not match what the GNU tools use, which would either be `arm-linux-gnueabi-` or `arm-linux-gnueabihf-`, depending on what tools you have available in your PATH, which causes clang not to find the appropriate tools and fall back to the hosts (which is a known pain point, see #476).

**Comment by n8v8R** [comment]
Of course, now that you mentioned it makes sense that when mixing the different toolsets. The is not present with `arm-linux-gnueabihf-`
