### ISSUE TITLE
invalid instruction in arch/arm/kernel/hyp-stub.S

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1155]
testing our ARMv6 CI config (aspeed_g5_defconfig) on linux-next with LLVM_IAS=1:
```
arch/arm/kernel/hyp-stub.S:146:2: error: invalid instruction, any one of the following would fix this:
 ubfx r7, r7, #16, #4                                                                                                                                                                      
 ^
arch/arm/kernel/hyp-stub.S:146:2: note: instruction requires: armv6t2                                                                                                                      
 ubfx r7, r7, #16, #4                                                                                                                                                                      
 ^
arch/arm/kernel/hyp-stub.S:146:2: note: instruction requires: thumb2                                                                                                                       
 ubfx r7, r7, #16, #4                                                                                                                                                                      
 ^
```

**Comment by jcai19** [comment]
I reproduced it locally, the exact command that caused this issue is as follows,

clang -Wp,-MMD,arch/arm/kernel/.hyp-stub.o.d -nostdinc -isystem /media/storage/jiancai/llvm-project/build/release/lib/clang/12.0.0/include -I./arch/arm/include -I./arch/arm/include/generated  -I./include -I./arch/arm/include/uapi -I./arch/arm/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Qunused-arguments -D__ASSEMBLY__ -fno-PIE --target=arm-linux-gnueabihf --prefix=/usr/bin/arm-linux-gnueabihf- --gcc-toolchain=/usr -Werror=unknown-warning-option -mabi=aapcs-linux -mfpu=vfp -funwind-tables -meabi gnu -marm -Wa,-W -D__LINUX_ARM_ARCH__=6 -march=armv6k -mtune=arm1136j-s -include asm/unified.h -msoft-float -Wa,-gdwarf-2 -Wa,-march=armv7-a    -c -o arch/arm/kernel/hyp-stub.o arch/arm/kernel/hyp-stub.S
clang-11: warning: argument unused during compilation: '-march=armv6k' [-Wunused-command-line-argument]
clang-11: warning: argument unused during compilation: '-Wa,-march=armv7-a' [-Wunused-command-line-argument]
arch/arm/kernel/hyp-stub.S:146:2: error: invalid instruction, any one of the following would fix this:
 ubfx r7, r7, #16, #4
 ^
arch/arm/kernel/hyp-stub.S:146:2: note: instruction requires: armv6t2
 ubfx r7, r7, #16, #4
 ^
arch/arm/kernel/hyp-stub.S:146:2: note: instruction requires: thumb2
 ubfx r7, r7, #16, #4


Note the warnings about the unused flags. I assume in this case the intended target triple for the assemble to use should be '-Wa,-march=armv7-a'?

$ cat foo.s 
ubfx r7, r7, #16, #4
$ llvm-mc -triple=armv7a -filetype=obj -o foo.o foo.s
$ arm-linux-gnueabihf-objdump -d foo.o 

foo.o:     file format elf32-littlearm


Disassembly of section .text:

00000000 <.text>:
   0:	e7e37857 	ubfx	r7, r7, #16, #4

**Comment by nickdesaulniers** [comment]
I suspect this is fixed by https://reviews.llvm.org/rG1d51c699b9e2ebc5bcfdbe85c74cc871426333d4. TODO: verify

**Comment by nickdesaulniers** [comment]
(dupe of #1195)
