### ISSUE TITLE
clang build pass but failed to boot-up on qemu

### ISSUE THREAD

**Issue by unicornx** [ClangBuiltLinux/linux#1162]
my environment description:
- QEMU：5.1.0 built from source
- riscv-gnu-toolchain: built from source, just pull from github several days ago and should be very latest, commit id: 7f1f4ab5b0e04f267a197c2e99449de775891a4d
- llvm/clang: built from source, branch release/10.x

I am doing some experiment to use clang to build linux for RISC-V and test with QEMU.
I find when for linux v5.4, build passed but can not boot from QEMU (switch to gnu toolchain totally, everything is ok). Then I use linux v5.9.0-rc4, build passed and can run on QEMU. The only concern is I see many warning "-save-restore' is not a recognized feature for this target (ignoring feature)", not sure if any impaction.
Then I double checked and find v5.6 failed, but since v5.7, all versions success.

my build command for your reference:
```
make ARCH=riscv CC=../../llvm-project/install/bin/clang defconfig
make ARCH=riscv CC=../../llvm-project/install/bin/clang CROSS_COMPILE=riscv64-unknown-linux-gnu- -j $(nproc)
```

My question is, what's in kernel or in clang that blocks me from building 5.4/5.6 and run on QEMU. Though it pass build but I think there should be something wrong in kernel. Or is there any story behind this what I missed, due to I see when I upgrade the kernel version, it works?

Thanks in adv.

**Comment by unicornx** [comment]
Oh， I'm afraid it is related to  Supervisor Binary Interface changes.

Because I see when my QEMU launches, it print out following info, and it says `Runtime SBI Version    : 0.2`:
```
OpenSBI v0.7
   ____                    _____ ____ _____
  / __ \                  / ____|  _ \_   _|
 | |  | |_ __   ___ _ __ | (___ | |_) || |
 | |  | | '_ \ / _ \ '_ \ \___ \|  _ < | |
 | |__| | |_) |  __/ | | |____) | |_) || |_
  \____/| .__/ \___|_| |_|_____/|____/_____|
        | |
        |_|

Platform Name          : QEMU Virt Machine
Platform HART Features : RV64ACDFIMSU
Current Hart           : 0
Firmware Base          : 0x80000000
Firmware Size          : 128 KB
Runtime SBI Version    : 0.2
```

And I checked the kernel version changes log @ https://kernelnewbies.org/Linux_5.7#RISC-V, since v5.7, kernel `Add Supervisor Binary Interface 0.2 and CPU hotplug`.  I'm afraid it is the rootcause. If anybody knows about this, please help confirm, thanks in adv.

**Comment by nickdesaulniers** [comment]
> My question is, what's in kernel or in clang that blocks me from building 5.4/5.6 and run on QEMU.

We don't support risc-v on 5.4; only mainline and linux-next.  https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/builds/186621377

My guess for 5.4/5.6 would be #867.  Can you please test cherry-picking https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6c58f25e6938c073198af8b1e1832f83f8f0df33?  If that works, then we can send a backport of it to stable.

Booting riscv is currently disabled due to https://github.com/ClangBuiltLinux/continuous-integration/pull/307. cc @nathanchance 

I'm trying to work with folks from SiFive and lowRISC to help own coverage here.

**Comment by unicornx** [comment]
@nickdesaulniers I think the issue I mentioned here is not the same as that of #867 . Actually what I saw is the QEMU can not boot into kernel from bootloader, due to I only see log from SBI, but no log from kernel when booting. (#867 is failed to boot when mounting rootfs, right?) Below is what I see on my terminal when run qemu.
```
u@u:~/ws/riscv64-linux$ qemu-system-riscv64 -M virt -m 256M -nographic -kernel linux/arch/riscv/boot/Image -drive file=rootfs.img,format=raw,id=hd0  -device virtio-blk-device,drive=hd0 -append "root=/dev/vda rw console=ttyS0"

OpenSBI v0.7
   ____                    _____ ____ _____
  / __ \                  / ____|  _ \_   _|
 | |  | |_ __   ___ _ __ | (___ | |_) || |
 | |  | | '_ \ / _ \ '_ \ \___ \|  _ < | |
 | |__| | |_) |  __/ | | |____) | |_) || |_
  \____/| .__/ \___|_| |_|_____/|____/_____|
        | |
        |_|

Platform Name          : QEMU Virt Machine
Platform HART Features : RV64ACDFIMSU
Current Hart           : 0
Firmware Base          : 0x80000000
Firmware Size          : 128 KB
Runtime SBI Version    : 0.2

MIDELEG : 0x0000000000000222
MEDELEG : 0x000000000000b109
PMP0    : 0x0000000080000000-0x000000008001ffff (A)
PMP1    : 0x0000000000000000-0xffffffffffffffff (A,R,W,X)
QEMU: Terminated
u@u:~/ws/riscv64-linux$ 
```

I also checked the code of v5.7, and it does not contain the patch you mentioned (6c58f25e6938c073198af8b1e1832f83f8f0df33).   And v5.7 can boot successfully.  I also tried cherry-picking of the patch and applied on v5.4, the same issue without any improvement.

What I see is, 5.4/5.5/5.6 failed, but since 5.7, 5.8 and 5.9-rc4 can boot. That‘s why I doubt if it is related to the changes in v5.7 ("Add Supervisor Binary Interface 0.2 and CPU hotplug").

But the real concern I have here is why for kernel **v5.4**, if I build with GNU-toolchian, kernel can boot, but after I change to LLVM, it fails. There should exits some other issue in something.

BTW: Is there any requirements from build env setting? I see you use `BOOT=false` and `LLVM_IAS=1` in CI building. What are they for?

**Comment by nickdesaulniers** [comment]
> Linux v5.4/5.5/5.6 pass build but failed boot with QEMU. Linux can boot for v5.7, 5.8 and 5.9-rc4.

Thanks for the report.  There's no process for backporting patches to LTS branches that are unsupported; we only support the currently supported branches of the stable tree.  At this time, that's 4.4, 4.9, 4.14, 4.19, and 5.4.

> why for kernel v5.4, if I build with GNU-toolchian, kernel can boot, but after I change to LLVM, it fails.

We only got RISC-V + LLVM working around the 5.8 release, so I wouldn't expect any older release to work.  If you can identify the patches that need backporting, great! Please send them to the stable kernel mailing list and we'll add that ISA to our CI to ensure we keep it building.  But at this time, there's little incentive to backport RISC-V support to branches where it didn't already work.

> Is there any requirements from build env setting?

https://www.kernel.org/doc/html/latest/kbuild/llvm.html

> I see you use BOOT=false and LLVM_IAS=1 in CI building. What are they for? I don't use them in my building of kernel.

Right; they're specific to the `driver.sh` file in there, which controls which target to build for TravisCI.  `BOOT=false` prevents the driver from trying to boot test the resulting image in QEMU for cases where we don't boot successfully.  `LLVM_IAS=1` uses clang's integrated assembler rather than GNU `as` to assemble assembly sources.  We've only recently got its support up to par, so you wont see it used for many older branches.
