### ISSUE TITLE
call to X() leaves .noinstr.text section

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1169]
forked from #1125. (I don't know yet if they're conflated). ToT clang + mainline or next.

```
  LD      vmlinux.o
  OBJTOOL vmlinux.o
vmlinux.o: warning: objtool: __do_fast_syscall_32()+0x49: call to syscall_enter_from_user_mode_work() leaves .noinstr.text section
vmlinux.o: warning: objtool: do_machine_check()+0x288: call to mce_panic() leaves .noinstr.text section
vmlinux.o: warning: objtool: rcu_nmi_enter()+0xd6: call to __SCT__tp_func_rcu_dyntick() leaves .noinstr.text section
```

`./tools/testing/ktest/config-bisect.pl` says
```
Difference between good (+) and bad (-)
-VMLINUX_VALIDATION=y
 DEBUG_ENTRY n -> y
```

(enabling the latter selects the former). So defconfig+the above. #1125 mentioned llvm commit 4b0aa5724feaa89a9538dcab97e018110b0e4bc3, so if I sync back to just before that (c430c21202c377cfb9fce0e7272f7208d1e8a531), I can repro.  So 4b0aa5724feaa89a9538dcab97e018110b0e4bc3 is unrelated.

**Comment by melver** [comment]
I think there are some known warnings still around (CONFIG_DEBUG_ENTRY enables these checks which I've put in all my configs because sanitizers have been prone to trigger them).

It's due to the new x86 entry code which requires noinstr functions to transitively call only noinstr functions. x86@kernel.org folks are working on it.

There's some whack-a-mole going on with these unfortunately, as not all configs show the same warnings. While they should be resolved, most of them can currently be tolerated AFAIK.

We should check if they exist also with GCC. What I've seen is that the main reason there's a difference between compilers is due to inlining behaviour. The fix for these is usually something like adding an __always_inline: https://lkml.kernel.org/r/159851487420.20229.1106109799847028466.tip-bot2@tip-bot2

**Comment by nathanchance** [comment]
`x86_64_defconfig` + `CONFIG_DEBUG_ENTRY=y` shows no objtool warnings with ToT LLVM and Linux. `git log --oneline --grep="leaves .noinstr.text section"` shows several commits that appear to address this. Closing for now.
