### ISSUE TITLE
Link failure aarch64-linux-ld: .init.data has both ordered  and unordered sections

### ISSUE THREAD

**Issue by arndb** [ClangBuiltLinux/linux#1206]
This is an arm64 randconfig build with clang-12 and GNU binutils:

/home/arnd/cross/x86_64/gcc-10.1.0-nolibc/aarch64-linux/bin/aarch64-linux-ld: .init.data has both ordered [`__patchable_function_entries' in init/main.o] and unordered [`.meminit.data' in mm/page_alloc.o] sections
/home/arnd/cross/x86_64/gcc-10.1.0-nolibc/aarch64-linux/bin/aarch64-linux-ld: final link failed: bad value
make[2]: *** [/git/arm-soc/Makefile:1140: vmlinux] Error 1

.config at https://pastebin.com/BvaZiFqN

**Comment by nickdesaulniers** [comment]
cc @DanielKristofKiss (I suspect this is related to BTI)

**Comment by DanielKristofKiss** [comment]
BTI has no effect on the data sections.
patchable_function_entries has alignment 8 while I don't see any alignment for .meminit.data in the section and I guess the linker script puts them together. 

These are the interesting configs
CC_USING_PATCHABLE_FUNCTION_ENTRY
CONFIG_DYNAMIC_FTRACE
CONFIG_ARCH_ENABLE_MEMORY_HOTPLUG

Config need to be spinned, I just skimmed thru the code.

**Comment by arndb** [comment]
I confirmed that it shows up with both tinyconfig and defconfig after enabling CONFIG_DYNAMIC_FTRACE. Interestingly this only happens with 'make LLVM_IAS=1 LLVM=' but not when using LLVM=1

**Comment by nickdesaulniers** [comment]
@MaskRay what does it mean for sections to be ordered? Is this related to input sections specified in a linker script being a mix of ordered and not, when being grouped together into one output section?

**Comment by MaskRay** [comment]
This is expected. 

LLD is more relaxed on mixed SHF_LINK_ORDER & non-SHF_LINK_ORDER after https://reviews.llvm.org/D84001
GNU ld does not support mixed SHF_LINK_ORDER & non-SHF_LINK_ORDER input sections in one output section. The feature request to relax it: https://sourceware.org/bugzilla/show_bug.cgi?id=26256

GCC -fpatchable-function-entry had severe design flaws (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93195 https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93197). When I implement -fpatchable-function-entry, I carefully and deliberately chose SHF_LINK_ORDER to fix these problems but the result is GNU ld (due to unimplemented https://sourceware.org/bugzilla/show_bug.cgi?id=26256) may error. Perhaps someone can ping on https://sourceware.org/pipermail/binutils/2020-August/112732.html :)

(From https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93195#c7 , it seems that newer GCC may use SHF_LINK_ORDER as well.)

One workaround on the kernel side is to allocate an output section dedicated to SHF_LINK_ORDER sections.

**Comment by MaskRay** [comment]
From binutils 2.36 onwards, GNU ld will support mixed SHF_LINK_ORDER and non-SHF_LINK_ORDER input sections in an output section https://sourceware.org/bugzilla/show_bug.cgi?id=26256

**Comment by nickdesaulniers** [comment]
> Interestingly this only happens with 'make LLVM_IAS=1 LLVM=' but not when using LLVM=1

Confirmed:

```sh
$ wget https://pastebin.com/raw/BvaZiFqN -O .config
$ ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- make CC=clang -j72 olddefconfig
$ ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- make CC=clang LLVM_IAS=1 -j72 vmlinux -s
aarch64-linux-gnu-ld: .init.data has both ordered [`__patchable_function_entries' in init/main.o] and unordered [`.meminit.data' in mm/page_alloc.o] sections
```
This is with 
```sh
$ aarch64-linux-gnu-ld --version
GNU ld (GNU Binutils for Debian) 2.35.2
```
testing with ToT binutils @ 2.36.50.20210428, I can no longer reproduce.

So folks can avoid this by either:
- use LLVM=1 when building with LLVM_IAS=1, or
- upgrade aarch64-linux-gnu-ld to 2.36
