### ISSUE TITLE
get off freenode

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1402]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/MAINTAINERS#n4442 and https://clangbuiltlinux.github.io/ both say we're using freenode. I just tried to connect and got banned...not sure precisely what's going on, or if this is related to their current drama.

**Comment by nathanchance** [comment]
Looks like someone created `#clangbuiltlinux` on [libera.chat](https://libera.chat) as I can join it and there are several people in there already.

While we are at it, should we point people at Telegram and Discord through MAINTAINERS? I am personally more active on those platforms rather than IRC because I have other projects/chats on there so I am going to be more accessible there. We have talked about canning Telegram in favor of Discord, although I do not like the mobile notifications situation with Discord (because of how large the LLVM channel, the "All Message" option for particular channels does not work for mobile notifications).

**Comment by nathanchance** [comment]
https://github.com/ClangBuiltLinux/ClangBuiltLinux.github.io/pull/27 for our website.
