### ISSUE TITLE
arch/mips/sgi-ip22/Platform:28: *** gcc doesn't support needed option -mr10k-cache-barrier=store.  Stop.

### ISSUE THREAD

**Issue by emojifreak** [ClangBuiltLinux/linux#1543]
This is in response to 
https://lore.kernel.org/lkml/CAK7LNAS7=qYs7NdDRY+4Dz5Zt0tLDo-W-EMcx+9TaNazNVcX=Q@mail.gmail.com/

`CONFIG_SGI_IP28` and `LLVM_IAS=1` causes the following build error:

```
arch/mips/sgi-ip22/Platform:28: *** gcc doesn't support needed option -mr10k-cache-barrier=store.  Stop.
```

This can be reproduced by the following script. By the way, I do not expect machine-specific configurations in the mips architecture are buildable by `LLVM_IAS` as nobody seems to test or have interest in using LLVM_IAS with those machine-specific configs. I wonder if build errors with `LLVM_IAS=1` and configs other than generic mips machine should be reported here. 

```
#!/bin/sh

KVER=5.16-rc4
LANG=C.UTF-8
export LANG
cd /var/tmp/tmp26sgiip28

  cat >/tmp/config$$.txt <<EOF
CONFIG_FTRACE_MCOUNT_USE_RECORDMCOUNT=n
CONFIG_KASAN=n
CONFIG_GCOV_KERNEL=n
CONFIG_COMPILE_TEST=n
CONFIG_TRIM_UNUSED_KSYMS=n
CONFIG_SHADOW_CALL_STACK=y
CONFIG_LD_DEAD_CODE_DATA_ELIMINATION=n
CONFIG_INIT_STACK_ALL_ZERO=y
CONFIG_KVM=y
CONFIG_PREEMPT=y
CONFIG_PREEMPT_DYNAMIC=y
CONFIG_UBSAN_OBJECT_SIZE=n

CONFIG_WERROR=n
CONFIG_EMBEDDED=n

CONFIG_DEBUG_INFO=y
CONFIG_DEBUG_INFO_DWARF5=y
CONFIG_DEBUG_INFO_COMPRESSED=y
CONFIG_DEBUG_INFO_BTF=y

CONFIG_ACPI=y
CONFIG_EFI_STUB=y
CONFIG_EFI=y
CONFIG_DMI=y
CONFIG_NUMA=y
CONFIG_MEMORY_HOTPLUG=y
CONFIG_HOTPLUG_PCI=y
CONFIG_HOTPLUG_PCI_PCIE=y
CONFIG_HOTPLUG_CPU=y

CONFIG_SGI_IP28=y
CONFIG_CPU_R10000=y

CONFIG_XILINX_SDFEC=n
CONFIG_HIBERNATION=y
CONFIG_MIPS_CPS=y
CONFIG_CPU_HAS_MSA=y
CONFIG_RELOCATABLE=n
CONFIG_RELOCATION_TABLE_SIZE=0x01000000
CONFIG_KEXEC=n
CONFIG_CPU_LITTLE_ENDIAN=y
CONFIG_CPU_BIG_ENDIAN=n
CONFIG_32BIT=n
CONFIG_64BIT=y
CONFIG_MIPS32_O32=n
CONFIG_MIPS32_N32=y
CONFIG_CRYPTO_CRC32_MIPS=n
CONFIG_CRYPTO_CHACHA_MIPS=n
CONFIG_CRYPTO_POLY1305_MIPS=m

CONFIG_LKDTM=n

EOF


for a in mips; do
  rm -rf /var/tmp/tmp26sgiip28/$a
  mkdir /var/tmp/tmp26sgiip28/$a
  cd /var/tmp/tmp26sgiip28/$a
  exec </dev/null >build-log-${KVER}-${a}.txt 2>&1
  set -xe
  tar zxf /var/tmp/linux-${KVER}.tar.gz
  cd linux-${KVER}

#  sed -i 's/-O2/-O3/g' Makefile
#  sed -i 's/-Os/-Oz/g' Makefile
  cp /tmp/config$$.txt .config
  make LLVM=1 LLVM_IAS=1 CROSS_COMPILE=mips64el-linux-gnuabi64- CROSS_COMPILE_COMPAT=mipsel-linux-gnu- allmodconfig
#  make CROSS_COMPILE=mips64el-linux-gnuabi64- CROSS_COMPILE_COMPAT=mipsel-linux-gnu- allmodconfig
  cat /tmp/config$$.txt >>.config

  yes '' |
#    chrt --idle 0 nice -19 make -j 5 --keep-going ARCH=$a CROSS_COMPILE=mips64el-linux-gnuabi64- CROSS_COMPILE_COMPAT=mipsel-linux-gnu-   all &
    chrt --idle 0 nice -19 make -j 5 --keep-going ARCH=$a LLVM=1 LLVM_IAS=1 CROSS_COMPILE=mips64el-linux-gnuabi64- CROSS_COMPILE_COMPAT=mipsel-linux-gnu- KCFLAGS="-mllvm -polly-ast-use-context -mllvm -polly-invariant-load-hoisting -mllvm -polly-opt-fusion=max -mllvm -polly-run-inliner -mllvm -polly-vectorizer=stripmine -mllvm -polly-run-dce"  all &
  exec </dev/null >/dev/null 2>&1
done 
wait
```

**Comment by nathanchance** [comment]
> I wonder if build errors with LLVM_IAS=1 and configs other than generic mips machine should be reported here.

Reports are never bad since issues are free but realistically, it is not likely that these option/flags will be implemented unless someone steps up from the MIPS or LLVM communities. As far as I am aware, this project does not have a whole ton of people interested in MIPS and we have enough bugs/issues/feature requests for the architectures that are more alive (ARM/x86). The MIPS community in the Linux kernel seems to be tightly coupled to GCC (as one can see by all of the flags implemented in GCC that are not in LLVM) so there probably won't be much help there but I won't ever say never :) Getting people involved is one of the long term goals of the project and issues like this can help attract interest so I don't think there is any reason to hold back filing them. Perhaps we should instead file a single bug for all of the unimplemented flags that you find in the MIPS port so that if someone wants to take a look at implementing them, they have one place to look and can file separate bugs after they start working on them?

**Comment by emojifreak** [comment]
Thank you for sharing your view. Another related issue is the Rust support in Linux. Currently it seems to require `CC=clang` at least. So build failure with `CC=clang` is probably worth reporting...

**Comment by nathanchance** [comment]
> Perhaps we should instead file a single bug for all of the unimplemented flags that you find in the MIPS port so that if someone wants to take a look at implementing them, they have one place to look and can file separate bugs after they start working on them?

I have opened #1544 to track further missing flags in `clang` and the integrated assembler.

We can keep this open because that `error` call should be removed like #1529 (I am hoping Tiezhu will do this as a part of [MIPS: Makefile: Remove "ifdef need-compiler" for Kbuild.platforms](https://lore.kernel.org/r/1639109105-1545-1-git-send-email-yangtiezhu@loongson.cn/), I can do it later if not).

**Comment by nathanchance** [comment]
Tiezhu submitted https://lore.kernel.org/r/1639389477-17586-2-git-send-email-yangtiezhu@loongson.cn/.

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/mips/c/048cc2378c2494519d940597629465b3ea44a96f

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/048cc2378c2494519d940597629465b3ea44a96f
