### ISSUE TITLE
error: .fnstart must precede ... directive in arch/arm/probes/kprobes/core.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1718]
After commit [1069c1dd20a3](https://git.kernel.org/next/linux-next/c/1069c1dd20a3071fb2bc44e2f46598d62a50b3fc) ("ARM: 9231/1: Recover kretprobes return address for EABI stack unwinder"), the following error occurs when building `ARCH=arm allmodconfig`:

```
arch/arm/probes/kprobes/core.c:409:30: error: .fnstart must precede .save or .vsave directives
                "stmdb  sp, {sp, lr, pc}        \n\t"
                                                  ^
<inline asm>:3:2: note: instantiated into assembly here
        .save   {sp, lr, pc}
        ^
arch/arm/probes/kprobes/core.c:412:29: error: .fnstart must precede .pad directive
                "stmdb  sp!, {r0 - r11}         \n\t"
                                                  ^
<inline asm>:6:2: note: instantiated into assembly here
        .pad    #52
        ^
2 errors generated.
```

Is this an integrated assembler bug or is the code wrong? GNU as accepts it without any issues. It looks like the integrated assembler has had this behavior since support for these directives was added:

https://github.com/llvm/llvm-project/commit/4ea23b56c50da5e8c59604190bb1b145e4b3a335

**Comment by nickdesaulniers** [comment]
Perhaps we need to add explicit `.fnstart`/``.fnend` directives to the inline asm within `__kretprobe_trampoline`?
https://sourceware.org/binutils/docs/as/ARM-Unwinding-Tutorial.html
But the compiler should be emitting `.fnstart` for all functions for arm. Simplified test case:
https://godbolt.org/z/PYTEq6Wss

**Comment by loganchien** [comment]
[nickdesaulniers](https://github.com/nickdesaulniers) and I had an offline discussion.  My current guess is that the AsmParser for the inline assembly doesn't have the context (a `.fnstart` should be generated as a part of the prologue of the `__kretprobe_trampoline` function).  AsmPrinterInlineAssembly creates a [new instance of MCAsmParser](https://github.com/llvm-mirror/llvm/blob/2c4ca6832fa6b306ee6a7010bfb80a3f2596f824/lib/CodeGen/AsmPrinter/AsmPrinterInlineAsm.cpp#L138) and each instance has its own [UnwindContext](https://github.com/llvm-mirror/llvm/blob/2c4ca6832fa6b306ee6a7010bfb80a3f2596f824/lib/Target/ARM/AsmParser/ARMAsmParser.cpp#L186), which keeps track of `.fnstart` and `.fnend` directives.

One possible compiler fix is to move `UnwindContext` to somewhere else so that it can be shared by multiple instances of AsmParser.  However, it may take time to figure out a right solution and get it landed.

In the meantime, I think an easier fix is to rewrite `__kretprobe_trampoline` completely in assembly.  Since there is no non-assembly code, (IMO) we are getting very little benefit from using `asm volatile (...)` inline assembly syntax.

**Comment by nathanchance** [comment]
Upstream report: https://lore.kernel.org/CA+G9fYvyD9OWF53ua2EZmyf+=YTx4f1mezDNkVLMxf3BKXW=_w@mail.gmail.com/

**Comment by nickdesaulniers** [comment]
filed: https://github.com/llvm/llvm-project/issues/57993 against llvm

**Comment by nickdesaulniers** [comment]
sent: https://lore.kernel.org/llvm/20220926183725.1112298-1-ndesaulniers@google.com/

**Comment by nickdesaulniers** [comment]
[v3](https://lore.kernel.org/llvm/20220930211505.209939-1-ndesaulniers@google.com/) has [some comments](https://lore.kernel.org/llvm/CAMj1kXHCGjb-mWHh37wv2mgZvLEsRA=f_Y-7UMom-QiRjTJ_Nw@mail.gmail.com/) that will necessitate a v4, but weirdly the base commit is not in -next today. [It looks like Russell picked it up](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=1069c1dd20a3071fb2bc44e2f46598d62a50b3fc), but [it's not in -next](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/tree/arch/arm/probes/kprobes/core.c#n368) today, and [RMK's patch tracker](https://www.arm.linux.org.uk/developer/patches/section.php?section=20page=137) wont load anything other than the first page for me.

**Comment by nickdesaulniers** [comment]
Looks like it was moved to discarded: https://www.arm.linux.org.uk/developer/patches/viewpatch.php?id=9231/1

**Comment by nickdesaulniers** [comment]
https://lore.kernel.org/linux-arm-kernel/YzHPGvhLkdQcDYzx@shell.armlinux.org.uk/

**Comment by nickdesaulniers** [comment]
Closing this for now since the offending patch in linux-next was discarded. May reopen imminently to track the ultimate fix though.
