### ISSUE TITLE
CFI: Implement -Wincompatible-function-pointer-types-strict

### ISSUE THREAD

**Issue by samitolvanen** [ClangBuiltLinux/linux#1745]
[`-Wcast-function-type-strict`](https://reviews.llvm.org/D134831) only checks explicit casts. To avoid CFI tripping type mismatches slipping through (e.g. issue https://github.com/ClangBuiltLinux/linux/issues/1703), we also need to implement a stricter version of `-Wincompatible-function-pointer-types`.

At a quick glance, `checkPointerTypesForAssignment` in `clang/lib/Sema/SemaExpr.cpp` looks like the place for this check.

cc @kees @nathanchance

**Comment by samitolvanen** [comment]
First draft: https://reviews.llvm.org/D136790

**Comment by nathanchance** [comment]
Having it be enabled automatically for CFI is probably fine but it might not be worth the effort. I think we want this warning to always be an error for the kernel so that automated testing catches as many issues as we can, regardless of what `CONFIG_CFI_CLANG` is set to, meaning we will still want to add it to `KBUILD_CFLAGS`. Otherwise, I would be fine with having it on by default but that means that we will need to delay merging this change until all instances have been fixed or explicitly turn it off for non-`W=1` builds.

**Comment by samitolvanen** [comment]
That's a valid point.  Would you mind posting a comment to Phabricator as well?  I think Aaron was also thinking about Clang CFI users outside the kernel, who would benefit from the warning being enabled by default.

**Comment by nathanchance** [comment]
Yup, sure thing!

**Comment by samitolvanen** [comment]
Merged: https://reviews.llvm.org/rG41ce74e6e983
Let's see if it will stay in...
