### ISSUE TITLE
-Wshift-overflow in drivers/pwm/pwm-tegra.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1759]
cros://chromeos-5.10/armel/chromiumos-arm.flavour.config (arm, clang-13) — FAIL, 1 error, 0 warnings, 0 section mismatches

Errors:
    drivers/pwm/pwm-tegra.c:148:53: error: signed shift result (0x3B9ACA0000) requires 39 bits to represent, but 'long' only has 32 bits [-Werror,-Wshift-overflow]

**Comment by nathanchance** [comment]
I do not see this warning with clang-15 or clang-16, which is strange...

Reverse bisect points to commit [`48e1829874df`](https://github.com/llvm/llvm-project/commit/48e1829874df15fd57e731d4824604f28e177585) `("[Diagnostics] Fix inconsistent shift-overflow warnings in C++20")` in `clang`. That change seems to cause us to miss the `warn_shift_result_gt_typewidth` diagnostic at the end of `DiagnoseBadShiftValues()` in `clang/lib/Sema/SemaExpr.cpp` due to the `S.getLangOpts().isSignedOverflowDefined()`, as the kernel is built with `-fno-strict-overflow`, which implies `-fwrapv`... was skipping that diagnostic an intentional consequence of that change? I think we still want to see warnings around shifting numbers by greater than their width?

Regardless, someone else already sent a fix: https://lore.kernel.org/20221110114549.34121-1-steven.price@arm.com/

**Comment by nathanchance** [comment]
Now fixed in -next: https://git.kernel.org/next/linux-next/c/dd1f1da4ada5d8ac774c2ebe97230637820b3323
