### ISSUE TITLE
CFI: GCOV is missing types causing crash

### ISSUE THREAD

**Issue by joefradley** [ClangBuiltLinux/linux#1778]
Enabling CFI_CLANG and GCOV causes CFI to crash at boot:
```
[    2.160088] CFI failure at do_basic_setup+0x46/0x68 (target: __llvm_gcov_init+0x0/0x20; expected type: 0xa540670c)
[    2.164385] invalid opcode: 0000 [#1] PREEMPT SMP PTI
```

To repro:
 * CONFIG_CFI_CLANG=y
 * CONFIG_GCOV_KERNEL=y
 * CONFIG_GCOV_PROFILE_ALL=y

cc @samitolvanen

**Comment by samitolvanen** [comment]
Thanks for filing the issue!

As discussed, this is similar to issue #1742 and needs to be fixed in LLVM. It looks like we need to add type hashes to `__llvm_gcov_init`, `__llvm_gcov_writeout`, and `__llvm_gcov_reset`. However, as I mentioned in the other issue, on x86_64 we also need to fix the `patchable-function-prefix` mismatch in LLVM generated functions or indirect calls to them will always fail.

In the meanwhile, if you need both CFI and GCOV enabled, you can add `__nocfi` to `do_ctors` and `llvm_gcov_init` as a temporary workaround.

**Comment by nickdesaulniers** [comment]
> if you need both CFI and GCOV enabled, you can add __nocfi to do_ctors and llvm_gcov_init as a temporary workaround.

We should probably send that upstream for now?

**Comment by samitolvanen** [comment]
> We should probably send that upstream for now?

I don't think that's necessary, I'll try to get the LLVM fix out this week. I just have to merge https://reviews.llvm.org/D141172 first.

**Comment by samitolvanen** [comment]
LLVM fixes are in, I'll reopen if they end up getting reverted.
https://reviews.llvm.org/rGfd5e26270660
https://reviews.llvm.org/rGa78cfd590902

**Comment by nickdesaulniers** [comment]
Should we update KConfig to mark kCFI and GCOV incompatible on specific clang versions?

**Comment by nathanchance** [comment]
> Should we update KConfig to mark kCFI and GCOV incompatible on specific clang versions?

We should not need to, as kCFI is only in main, not a release branch yet, so we can assume people will upgrade their main-based compilers to get this fix.
