### ISSUE TITLE
Invalid or unknown z ISA extension: 'zifencei'

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1808]
After https://github.com/llvm/llvm-project/commit/22e199e6afb1263c943c0c0d4498694e15bf8a16, RISC-V builds using GNU binutils older than 2.36 (i.e., current Debian stable, which is what TuxSuite uses) fail with:

```
riscv64-linux-gnu-ld: -march=rv64i2p0_m2p0_a2p0_c2p0_zicsr2p0_zifencei2p0: Invalid or unknown z ISA extension: 'zifencei'
riscv64-linux-gnu-ld: failed to merge target specific data of file fs/efivarfs/file.o
riscv64-linux-gnu-ld: -march=rv64i2p0_m2p0_a2p0_c2p0_zicsr2p0_zifencei2p0: Invalid or unknown z ISA extension: 'zifencei'
riscv64-linux-gnu-ld: failed to merge target specific data of file fs/efivarfs/super.o
```

https://storage.tuxsuite.com/public/clangbuiltlinux/continuous-integration2/builds/2M5r1HzVI5BhnbtCzitcWytFr0q/build.log
https://lore.kernel.org/CA+G9fYt9T=ELCLaB9byxaLW2Qf4pZcDO=huCA0D8ug2V2+irJQ@mail.gmail.com/

It seems like we will need something similar to https://git.kernel.org/linus/b8c86872d1dc171d8f1c137917d6913cae2fa4f2 for `zicsr` and `zifencei` but @ConchuOD mentioned upstream we might need some additional handling depending on the ISA specification.

cc @asb, I do not really think there is much that LLVM can do about this since the assembling/compiling stage is distinct from the linking one in the kernel, so we will just have to make sure all the tools support the same ISA extension before using it. However, I did not want a repeat of #1777, hence the ping.

**Comment by nathanchance** [comment]
Sorry, had the wrong title copy and pasted :/

**Comment by ConchuOD** [comment]
@nathanchance I can't self assign this, can you assign me?

**Comment by asb** [comment]
Thanks for flagging @nathanchance.

CC @preames as well, as we've been discussing these issues a lot recently (and preames authored that patch to avoid a whole set of other breakage). We should have a think if there's anything we can/should do differently when invoking the linker, especially as the emitted object files should have the full march info embedded in build attributes anyway.

**Comment by ConchuOD** [comment]
>We should have a think if there's anything we can/should do differently when invoking the linker, especially as the emitted object files should have the full march info embedded in build attributes anyway.

yah, that may be problematic too, IIRC you can't emit anything into the object file that is not supported by the linker.

The discussion of the patch Nathan linked above mentions this: https://lore.kernel.org/all/mhng-99b62de8-5b5c-48f7-bd01-bca2a5a26064@palmer-ri-x1c9a/

**Comment by ConchuOD** [comment]
> @ConchuOD mentioned upstream we might need some additional handling depending on the ISA specification

We do a dance in arch/riscv/Makefile like so:
```
# Newer binutils versions default to ISA spec version 20191213 which moves some
# instructions from the I extension to the Zicsr and Zifencei extensions.
toolchain-need-zicsr-zifencei := $(call cc-option-yn, -march=$(riscv-march-y)_zicsr_zifencei)
riscv-march-$(toolchain-need-zicsr-zifencei) := $(riscv-march-y)_zicsr_zifencei
```
I'm not sure how you lot in LLVM land are dealing with "delights" like the extraction of zicsr & zifencei from i, but with binutils they used the old spec where they were contained in i until 2.37. In 2.38 they switched to 20191213 by default, hence the dance above. The kernel requires zicsr & zifencei, so we just do whatever will cause them to be built.

It looks like (for LLVM=1, last nights main@HEAD) LLVM is emitting the following in object files:
```
rv64i2p0_m2p0_a2p0_c2p0_zicbom1p0_zicsr2p0_zifencei2p0_zihintpause2p0
```
Binutils 2.35 doesn't understand that though & aborts. That said it wouldn't understand zicbom either, but the above is an LLVM=1 build.
I just tried bintuils 2.35 and gcc-13 and get a similar sort of issue *sigh*:
```
binutils-2.35/bin/riscv64-unknown-linux-gnu-ld: -march=rv64i2p0_m2p0_a2p0_c2p0_zmmul1p0: Invalid or unknown z ISA extension: 'zmmul'
```
zmmul is another can of worms, but I guess I need to go patch that one too! @palmer-dabbelt this is why I was asking you about it...

Anyways... since the kernel cannot operate without zicsr and zifencei, I'll go and experiment with the simplest case patch that Nathan suggested.
Hopefully IAS doesn't do something odd if the asm contains zicsr/zifencei stuff but the isa string doesn't :)

**Comment by asb** [comment]
> Binutils 2.35 doesn't understand that though & aborts. That said it wouldn't understand zicbom either, but the above is an LLVM=1 build.
> I just tried bintuils 2.35 and gcc-13 and get a similar sort of issue _sigh_:

Ah, I'd only tested with current binutils (2.39), where it seems ld has the behaviour we want to move lld towards (i.e. not rejecting extensions/versions it doesn't know about):

```
$ cat a.s
.section .riscv.attributes,"",@0x70000003
.byte 0x41
.long .Lend-.riscv.attributes-1
.asciz "riscv"  # vendor
.Lbegin:
.byte 1  # Tag_File
.long .Lend-.Lbegin
.byte 5  # Tag_RISCV_arch
.asciz "rv64i2p0_zmadeup1p0"
.Lend:

$ cat b.s
.section .riscv.attributes,"",@0x70000003
.byte 0x41
.long .Lend-.riscv.attributes-1
.asciz "riscv"  # vendor
.Lbegin:
.byte 1  # Tag_File
.long .Lend-.Lbegin
.byte 5  # Tag_RISCV_arch
.asciz "rv64i50p0_zanotherfake1p0"
.Lend:

$ riscv64-linux-gnu-as a.s -o a.o
$ riscv64-linux-gnu-as b.s -o b.o
$ riscv64-linux-gnu-ld a.o b.o
$ llvm-readobj --arch-specific a.out

File: a.out
Format: elf64-littleriscv
Arch: riscv64
AddressSize: 64bit
LoadName: <Not found>
BuildAttributes {
  FormatVersion: 0x41
  Section 1 {
    SectionLength: 53
    Vendor: riscv
    Tag: Tag_File (0x1)
    Size: 43
    FileAttributes {
      Attribute {
        Tag: 5
        TagName: arch
        Value: rv64i50p0_zmadeup1p0_zanotherfake1p0
      }
    }
  }
}
```

**Comment by ConchuOD** [comment]
> > Binutils 2.35 doesn't understand that though & aborts. That said it wouldn't understand zicbom either, but the above is an LLVM=1 build.
> > I just tried bintuils 2.35 and gcc-13 and get a similar sort of issue _sigh_:
> 
> Ah, I'd only tested with current binutils (2.39), where it seems ld has the behaviour we want to move lld towards (i.e. not rejecting extensions/versions it doesn't know about):

Since 87fdd7ac09b ("RISC-V: Stop reporting warnings for mismatched  extension versions") which landed in 2.38, ld just doesn't care about what you have, so ~all ld version checks in Linux stop there. For lld we have to match the version where something was introduced, so I certainly would appreciate the same behaviour as ld ;)

**Comment by nathanchance** [comment]
> so I certainly would appreciate the same behaviour as ld ;)

I think that is what https://reviews.llvm.org/D144353 is supposed to address.

**Comment by ConchuOD** [comment]
*sigh* I spent some more time looking at this today and I think things are just broken.

The cc-option-yn() that we do checks cc/as, and in this case llvm-17 supports zicsr & zifencei so they get emitted in the object files etc. ld-2.35 doesn't support zifencei and aborts with:
```
/stuff/toolchains/binutils-2.35/bin/riscv64-linux-gnu-ld: -march=rv64i2p0_m2p0_a2p0_c2p0_zicsr2p0_zifencei2p0: Invalid or unknown z ISA extension: 'zifencei'
/stuff/toolchains/binutils-2.35/bin/riscv64-linux-gnu-ld: failed to merge target specific data of file arch/riscv/purgatory/ctype.o
```

What does llvm-17 do if I don't pass _zicsr_zifencei in march? Things build fine, boot fine so I assume it do the sane thing and treat rv64i as rv64_zifencei_zicsr since RVI made a hames of that extraction? I've been running ias-17, clang-17 and ld-2.35 successfully...

The reason I'm starting to think that this is just broken though is if gas needs those because it defaults to a spec version that requires setting zicsr_zifencei explicitly, but the linker doesn't support zicsr_zifencei we're going to be in trouble, see:
https://lore.kernel.org/all/20220126171442.1338740-1-aurelien@aurel32.net/
Either we will fail to build b/c of the assembler or linker, rock and a hard place!

My gut instinct is to say running that sort of mix & match binutils combo is just unsupported & fail the build if something prior to ld-2.38 is used with as-2.38, as in binutils-2.38 they stops caring about extensions in object files.

Assuming that if I pass -march=rv64i to the llvm tools that I get access to the same instructions as if I passed -march=rv64_zifencei_zicsr, we can just never add those extensions to the march string for ias.

I've still not got around to the 5.10 issue though, I don't really care about it all that much in comparison b/c I don't think (and hope!) that noone is shipping 5.10 kernels with things.
If they are, they can deal with the backports!

@nathanchance I'm not super familiar with 5.10 clang/llvm stuff, but I don't see ias in his config?
I would have thought that in that case, the cc-option-yn() would realise that gas-2.35 doesn't support the extensions. I'm probably too far down the rabbit hole right now to realise the obvious.

**Comment by nathanchance** [comment]
> I assume it do the sane thing and treat rv64i as rv64_zifencei_zicsr since RVI made a hames of that extraction?

If I am reading `llvm/docs/RISCVUsage.rst` correctly (emphasis mine):

> Between versions 2.0 and 2.1 of the base I specification, a backwards incompatible change was made to remove selected instructions and CSRs from the base ISA.  These instructions were grouped into a set of new extensions, but were no longer required by the base ISA.  This change is described in "Preface to Document Version 20190608-Base-Ratified" from the specification document.  LLVM currently implements version 2.0 of the base specification.  **Thus, instructions from these extensions are accepted as part of the base ISA.**

It sounds like that change you linked to ([mainline](https://git.kernel.org/linus/6df2a016c0c8a3d0933ef33dd192ea6606b115e3)) is not currently relevant to LLVM, as it implements 2.0 of the `i` specification vs. 2.1. For the immediate term, we could just gate the `toolchain-need-zicsr-zifencei` section on `AS_IS_GNU` since we know that it is only relevant when using GNU as? Of course, if LLVM decides to implement 2.1, then I guess we will be in the same boat but I suppose we could just move it into Kconfig like:

```
config AS_NEEDS_EXPLICIT_ZIFENCEI_ZICSR
	default y
	depends on (AS_IS_LLVM && AS_VERSION >= ...) || (AS_IS_GNU && AS_VERSION >= 23800)
```

Re-reading @asb's [post on Discourse](https://discourse.llvm.org/t/rfc-resolving-issues-related-to-extension-versioning-in-risc-v/68472), I saw the comment:

> - I observe that gcc will “correct” `-march=rv64i2p0_m2p0_a2p1_f2p2_d2p2_c2p0_zicsr2p0_zifencei2p0` to just `rv64i2p0_m2p0_a2p1_f2p2_d2p2_c2p0` in the assembly output. Is there any reason we’d want to adopt similar behaviour?

Would implementing that behavior in `clang` that help us here? I think so, since `_zicsr2p0_zifencei2p0` would not end up in the assembly output so GNU ld would not care, regardless of version. That clearly already works based on the fact that you were able to omit adding them with the combination you tried, right? I could be missing something though...

> if gas needs those because it defaults to a spec version that requires setting zicsr_zifencei explicitly, but the linker doesn't support zicsr_zifencei

Right, that would imply a different GNU/LLVM assembler and linker version, which I think is rather odd but I would not be surprised if that happened at some point :/

> I don't see ias in his config?

`LLVM_IAS=1` is set in the `make` command from what I can tell.

**Comment by ConchuOD** [comment]
> > I assume it do the sane thing and treat rv64i as rv64_zifencei_zicsr since RVI made a hames of that extraction?
> 
> If I am reading `llvm/docs/RISCVUsage.rst` correctly (emphasis mine):
> 
> > Between versions 2.0 and 2.1 of the base I specification, a backwards incompatible change was made to remove selected instructions and CSRs from the base ISA.  These instructions were grouped into a set of new extensions, but were no longer required by the base ISA.  This change is described in "Preface to Document Version 20190608-Base-Ratified" from the specification document.  LLVM currently implements version 2.0 of the base specification.  **Thus, instructions from these extensions are accepted as part of the base ISA.**
> 
> It sounds like that change you linked to ([mainline](https://git.kernel.org/linus/6df2a016c0c8a3d0933ef33dd192ea6606b115e3)) is not currently relevant to LLVM, as it implements 2.0 of the `i` specification vs. 2.1. For the immediate term, we could just gate the `toolchain-need-zicsr-zifencei` section on `AS_IS_GNU` since we know that it is only relevant when using GNU as? Of course, if LLVM decides to implement 2.1, then I guess we will be in the same boat but I suppose we could just move it into Kconfig like:
> 
> ```
> config AS_NEEDS_EXPLICIT_ZIFENCEI_ZICSR
> 	default y
> 	depends on (AS_IS_LLVM && AS_VERSION >= ...) || (AS_IS_GNU && AS_VERSION >= 23800)
> ```

I pretty much went and did this sort of thing earlier today:
https://github.com/ConchuOD/linux/commit/7a6639148068c6665b00a4e93161f50a29d5e070
I was going to just add `depends on AS_IS_GNU` though, since ias seems to do the right thing (at least for now).
I far prefer having these in Kconfig than in the Makefile, so that we can easily see what has happened after the fact!
If LLVM moves to a later version, and makes the same choices as the gnu folks, we can do something about IAS here too.

> Re-reading @asb's [post on Discourse](https://discourse.llvm.org/t/rfc-resolving-issues-related-to-extension-versioning-in-risc-v/68472), I saw the comment:
> 
> > * I observe that gcc will “correct” `-march=rv64i2p0_m2p0_a2p1_f2p2_d2p2_c2p0_zicsr2p0_zifencei2p0` to just `rv64i2p0_m2p0_a2p1_f2p2_d2p2_c2p0` in the assembly output. Is there any reason we’d want to adopt similar behaviour?
> 
> Would implementing that behavior in `clang` that help us here? I think so, since `_zicsr2p0_zifencei2p0` would not end up in the assembly output so GNU ld would not care, regardless of version. That clearly already works based on the fact that you were able to omit adding them with the combination you tried, right? I could be missing something though...

The combo I tried relies on LLVM having zicsr and zifencei as part of i. IFF that is true, we can control march in Linux's build system to ensure that
What we really do not want is things like seeing the i extension and then emitting zicsr_zifenci into the object files, cos there's nothing we can do to stop that.
If I ask for zicsr_zifencei, I'd probably expect to get it in march but as long as the assembler does the right thing I don't mind!

> > if gas needs those because it defaults to a spec version that requires setting zicsr_zifencei explicitly, but the linker doesn't support zicsr_zifencei
> 
> Right, that would imply a different GNU/LLVM assembler and linker version, which I think is rather odd but I would not be surprised if that happened at some point :/

Yah, the example I tried was gas 2.38 and ld 2.35. I see no real reason to obsess over those mixed types of configs, but if it ever comes up I'll just set things up so that a build ld < 2.38 chucks the toys.
$CC + a binutils/llvm tools revision needs to work, with all combinations of the tools enabled, but chasing these older mixed versions will be awful.

> > I don't see ias in his config?
> 
> `LLVM_IAS=1` is set in the `make` command from what I can tell.

I'm probably just too used to my recent kernels that put everything in the .config (super handy btw)

**Comment by preames** [comment]
> If I am reading `llvm/docs/RISCVUsage.rst` correctly (emphasis mine):
> 
> > Between versions 2.0 and 2.1 of the base I specification, a backwards incompatible change was made to remove selected instructions and CSRs from the base ISA.  These instructions were grouped into a set of new extensions, but were no longer required by the base ISA.  This change is described in "Preface to Document Version 20190608-Base-Ratified" from the specification document.  LLVM currently implements version 2.0 of the base specification.  **Thus, instructions from these extensions are accepted as part of the base ISA.**
> 
> It sounds like that change you linked to ([mainline](https://git.kernel.org/linus/6df2a016c0c8a3d0933ef33dd192ea6606b115e3)) is not currently relevant to LLVM, as it implements 2.0 of the `i` specification vs. 2.1. For the immediate term, we could just gate the `toolchain-need-zicsr-zifencei` section on `AS_IS_GNU` since we know that it is only relevant when using GNU as? Of course, if LLVM decides to implement 2.1, then I guess we will be in the same boat but I suppose we could just move it into Kconfig like:
To hopefully clarify.

At the moment, LLVM is defaulting to an older version of the specification from before Zifencei was split out.  As a result, FENCE.i is accepted with needing zifencei in a march string.  Up until my recent change, LLVM would fail if asked to compile with the zifencei extension explicitly.  The recent change modified LLVM to accept the zifencei, and pass it through to the ELF attributes.  This didn't change which instructions were accepted by the assembler at all, only how extension name was processed.

From the sound of it, the kernel build system was relying on the failure to detect the older spec mode.  As has been said up thread, we can simply avoid this check if we know we're compiling with LLVM.  

I was also pointed to another patch which tackles the issue another way.  See https://lore.kernel.org/all/mhng-a7fa6818-4d87-4a37-a17b-905376410809@palmer-ri-x1c9a/.  I'll leave it to others as to the preferred approach.  

All of this is working around a broken linker IMO - refusing to link just because of an unrecognized extension is extremely user hostile.  Seems like ld has recognized this in recent versions, and I expect we're going to take the same approach in lld.  (That's personal opinion and not something which has universal support in the project as of yet.)

**Comment by ConchuOD** [comment]
> I was also pointed to another patch which tackles the issue another way. See https://lore.kernel.org/all/mhng-a7fa6818-4d87-4a37-a17b-905376410809@palmer-ri-x1c9a/. I'll leave it to others as to the preferred approach.

FYI, this does not work for the problem in this thread! It does fix the issue with zmmul I pointed out above (or rather the v2 does).

> From the sound of it, the kernel build system was relying on the failure to detect the older spec mode. As has been said up thread, we can simply avoid this check if we know we're compiling with LLVM.

I ended up posting a patch to only add `zicsr_zifencei` to march for gas >= 2.38, there was never a need to do a cc-option check when we already know which versions of binutils are afflicted.

> All of this is working around a broken linker IMO - refusing to link just because of an unrecognized extension is extremely user hostile. Seems like ld has recognized this in recent versions, and I expect we're going to take the same approach in lld. (That's personal opinion and not something which has universal support in the project as of yet.)

As a user, the new ld behaviour is useful and my meaningless vote is in favour of ape-ing that!

**Comment by preames** [comment]
> > I was also pointed to another patch which tackles the issue another way. See https://lore.kernel.org/all/mhng-a7fa6818-4d87-4a37-a17b-905376410809@palmer-ri-x1c9a/. I'll leave it to others as to the preferred approach.
> 
> FYI, this does not work for the problem in this thread! It does fix the issue with zmmul I pointed out above (or rather the v2 does).

Oops, sorry for adding to the confusion!

**Comment by ConchuOD** [comment]
> > > I was also pointed to another patch which tackles the issue another way. See https://lore.kernel.org/all/mhng-a7fa6818-4d87-4a37-a17b-905376410809@palmer-ri-x1c9a/. I'll leave it to others as to the preferred approach.
> > 
> > 
> > FYI, this does not work for the problem in this thread! It does fix the issue with zmmul I pointed out above (or rather the v2 does).
> 
> Oops, sorry for adding to the confusion!

No worries. I initially thought it'd help too but didn't. I'll go do some more digging into it this week at some point hopefully.

**Comment by ConchuOD** [comment]
@nathanchance or @nickdesaulniers etc, could this be labeled "patch submitted" please?

**Comment by palmer-dabbelt** [comment]
I'm not really following the thread, but we could make GCC emit the 2.0-spec stuff via some command line option (maybe `-misa-spec-version`?).  We changed the default, but the old one should work.

**Comment by ConchuOD** [comment]
> I'm not really following the thread, but we could make GCC emit the 2.0-spec stuff via some command line option (maybe `-misa-spec-version`?). We changed the default, but the old one should work.

Maybe I don't understand, but I'm not sure what that gets us here. There is [another issue about 2p2 versions being emitted by gas](https://github.com/ClangBuiltLinux/linux/issues/1777) but it looks to have been taken care of.
In this issue, the problem is just a pre-2.38 binutils not understanding what zifencei is, unless of course I missed something.
When it comes to toolchains, that wouldn't be surprising.

**Comment by ConchuOD** [comment]
So.. [@palmer-dabbelt suggested](https://lore.kernel.org/linux-riscv/mhng-2a3f3a1d-d4ee-4227-ac5b-cc37c494372b@palmer-ri-x1c9a/) using -misa-spec to force gcc/binutils to use the same version of the ISA spec that LLVM is using ([I've taken that to be 2.2](https://discourse.llvm.org/t/specifying-unpriviledge-spec-version-misa-spec-gcc-flag-equivalent/66935)).

All seemed well and good, until I went to try replicate the [original issue](https://lore.kernel.org/linux-riscv/20220126171442.1338740-1-aurelien@aurel32.net/) that the kernel was trying to work around (that binutils from 2.38 defaults to a later version of the spec than 2.2).
I wasted far, far too long before realising that my bloody [toolchain was built using --with-isa-spec=2.2](https://github.com/riscv-collab/riscv-gnu-toolchain/commit/df6ecbe4ddb2a1a261b44af822d22f1253d3f0e4#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R147), so I'd not trip that problem in the first place :/

My fear though is the mixed clang + binutils builds having issues, but I wasn't actually able to trip those during my testing. I built binutils using the tc-build script (which, to my knowledge, doesn't build with a specific ISA version) and was able to build and run kernels successfully.
I expected that that build would fail, because passing `-Wa,-misa-spec=2.2` etc to clang fails, so I would have that though binutils would default to a no-no version of the ISA spec. It assembled though, so I'm kinda lost on that front!

The below builds for me with a --with-isa-spec=20191203 toolchain, so I'll go off and submit it I suppose, but I'd like to know why the mixed clang + binutils build has no problems!
```
diff --git a/arch/riscv/Makefile b/arch/riscv/Makefile
index 6203c3378922..2df7a5dc071c 100644
--- a/arch/riscv/Makefile
+++ b/arch/riscv/Makefile
@@ -57,10 +57,8 @@ riscv-march-$(CONFIG_ARCH_RV64I)     := rv64ima
 riscv-march-$(CONFIG_FPU)              := $(riscv-march-y)fd
 riscv-march-$(CONFIG_RISCV_ISA_C)      := $(riscv-march-y)c
 
-# Newer binutils versions default to ISA spec version 20191213 which moves some
-# instructions from the I extension to the Zicsr and Zifencei extensions.
-toolchain-need-zicsr-zifencei := $(call cc-option-yn, -march=$(riscv-march-y)_zicsr_zifencei)
-riscv-march-$(toolchain-need-zicsr-zifencei) := $(riscv-march-y)_zicsr_zifencei
+KBUILD_CFLAGS += $(call cc-option,-misa-spec=2.2)
+KBUILD_AFLAGS += $(call as-option,-Wa$(comma)-misa-spec=2.2)
 
 # Check if the toolchain supports Zihintpause extension
 riscv-march-$(CONFIG_TOOLCHAIN_HAS_ZIHINTPAUSE) := $(riscv-march-y)_zihintpause
```

**Comment by ConchuOD** [comment]
I sent a patch doing this now: https://lore.kernel.org/all/20230308220842.1231003-1-conor@kernel.org/

Hopefully easier to understand than my ramble in the call thing this evening!

**Comment by nathanchance** [comment]
I found another issue in my own testing, the solution to which I rolled up into what is effectively v3:

https://lore.kernel.org/20230313-riscv-zicsr-zifencei-fiasco-v1-1-dd1b7840a551@kernel.org/

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/riscv/c/e89c2e815e76471cb507bd95728bf26da7976430

**Comment by ConchuOD** [comment]
It's already in a PR to Linus too.
Probably want to leave this one open til it's backported though, right?

**Comment by nathanchance** [comment]
Yeah, especially since the 5.10 backports will be a little hairy and I won’t be able to get to them until next week.

**Comment by nathanchance** [comment]
Fix is now in mainline:

https://git.kernel.org/linus/e89c2e815e76471cb507bd95728bf26da7976430

I will handle backports later this week.

**Comment by ConchuOD** [comment]
> Fix is now in mainline:
> 
> https://git.kernel.org/linus/e89c2e815e76471cb507bd95728bf26da7976430
> 
> I will handle backports later this week.

Great, thanks for taking over Nathan :)

**Comment by nathanchance** [comment]
Backport to 5.10 submitted:

https://lore.kernel.org/20230328-riscv-zifencei-zicsr-5-10-v1-0-bccb3e16dc46@kernel.org/

5.15+ is in review right now.

5.4 is not buildable for RISC-V + `clang`, as it is missing [52e7c52d2ded](https://git.kernel.org/linus/52e7c52d2ded5908e6a4f8a7248e5fa6e0d6809a), [fdff9911f266](https://git.kernel.org/linus/fdff9911f266951b14b20e25557278b5b3f0d90d), and [abc71bf0a703](https://git.kernel.org/linus/abc71bf0a70311ab294f97a7f16e8de03718c05a) and I think binutils had issues at one point. Don't know, don't care, 5.4 is ancient :)

Closing this up for now.

**Comment by ConchuOD** [comment]
> Don't know, don't care, 5.4 is ancient

Yah, as I said in my email (which I think is off-list? it appeared to be off-lore at least) I don't think it is worth supporting such new tooling, in an awkward combo, for a kernel that doesn't contain support for any of the readily available hardware.
