### ISSUE TITLE
SORTTAB - Failed to sort kernel tables

### ISSUE THREAD

**Issue by ms178** [ClangBuiltLinux/linux#1842]
Hello Nathan, with clang 17.0.0 (1395cde24b3641e284bb1daae7d56c189a2635e3), I see issues compiling my customized 6.2.12 and 6.3.0 CachyOS-Kernel:

```
SORTTAB vmlinux
scripts/link-vmlinux.sh: line 195: 848887 Aborted  ${objtree}/scripts/sorttable ${1}
Failed to sort kernel tables
```
I am also on pahole-git: 1.25.r4.g31bc0d7. Is this a known issue? I couldn't find anything yet in the issue tracker. I had no trouble with earlier Clang snapshots and 6.2.12 last week, but that was on a different installation so there is a lot of room for error on my side.

Here is the [Link](https://github.com/ms178/archpkgbuilds/tree/main/packages/linux-cachyos) to my Kernel.

**Comment by nathanchance** [comment]
Hi @ms178, I am not sure how much time I will have to look at this today, but I recall hearing that there were some code generation issues in main the other day, have you tried rebuilding today to see if they were resolved? I built from 7be8341f19bfd9baf979ecadef22d1bcaa47b54e and have seen no issues across all the configurations that I test. I notice your kernel has patches that modify a lot of compiler flags, does the issue reproduce without them? I did not look too closely at the patches themselves but this issue seems similar to https://github.com/ClangBuiltLinux/linux/issues/1341, which was caused by changed defaults within `ld.lld`.

**Comment by ms178** [comment]
Thanks for the hint, @nathanchance. I'll try a newer Clang build later today and also will do some experiments without my aggressive CFLAGS. I'll report back with my findings. Until then, it is probably not worth it to spend too much of your time on this.

**Comment by ms178** [comment]
When using the CachyOS standard Flags (still: O3 + march=haswell in my case), I see the same problem plus these modpost warnings:

```
MODPOST Module.symvers
WARNING: modpost: vmlinux.o: section mismatch in reference: parse_args (section: .text.unlikely.parse_args.85345) -> do_early_param (section: .init.text)
WARNING: modpost: vmlinux.o: section mismatch in reference: parse_args (section: .text.unlikely.parse_args.85347) -> set_init_arg (section: .init.text)
WARNING: modpost: vmlinux.o: section mismatch in reference: bus_sort_breadthfirst (section: .text.bus_sort_breadthfirst.85398) -> pci_sort_bf_cmp (section: .init.text)
```
The toolchain I am seeing this error with comes from my llvm-bolt-scripts, so analyzing the other issue makes me think that using BOLT with -icf=1 with LLVM-17 might be a factor here. To test that theory, I'll try the default LLVM 15.0.7 next.

**Comment by nathanchance** [comment]
I brought up the modpost warnings in #1838 (I know I only mentioned arm64 and that one warning but the root cause is the same), I assume I do not see those in my builds due to `-O3` instead of the kernel's standard `-O2` or some other configuration differences, but they should be harmless.

I can try to reproduce the problem with just your configuration either later today or tomorrow as time permits.

**Comment by ms178** [comment]
Hm, with the default Clang 15.0.7 toolchain (and using my more aggressive CFLAGS-patches), the build also fails with the SORTTAB issue. That is not what I expected.

I also see this one additional warning which I didn't get with Clang-17:

```
 LD [M]  drivers/gpu/drm/amd/amdgpu/amdgpu.o
drivers/gpu/drm/amd/amdgpu/amdgpu.o: warning: objtool: dm_helpers_dp_mst_write_payload_allocation_table+0x1f4: stack state mismatch: cfa1=4+264 cfa2=5+16
```

I'll try to clean up more of my extra Kernel patches I carry around with. I'll also try using the default pahole next.

**Comment by ms178** [comment]
I've just reproduced the problem with a fresh LLVM-17 (BOLT) from today: 1f2d945f29950e6c794d013df58f256d48c90139 and also without any additional patches with the CachyOS 6.3.0 v4 sources and my config plus PKGBUILD. Also using the distro's default packages for bpf, perf, pahole and linux-api-headers didn't make a difference.

**Comment by ms178** [comment]
Just for reference, I also see this issue with the distro's GCC, so the chances are high that something else on my install is broken.

**Comment by nathanchance** [comment]
What is your host kernel version? I saw some discussion of a [`mm/` fix](https://git.kernel.org/linus/7e7757876f258d99266e7b3c559639289a2a45fe) needed for 6.3, which appeared in mainline this morning, could potentially be related?

**Comment by ms178** [comment]
I've tried both a custom build 6.2.12 and the distro 6.3.0 as my host Kernel with both showing the issue. CachyOS does carry quite a lot of extra patches on top, but can't tell if that is of relevance for this issue. I've also a BOLTed Ananicy-CPP installed and have seen some test failures on other programs related to the NICE-level. But I can't tell if that is of significance here, too.

Update: I've tried to patch the mentioned patch in but it doesn't make a difference on the compile job itself. I'll wait until a stable release gets pushed with that patch and will try again.

**Comment by ms178** [comment]
Good news, I finally got it to work. I am still a bit puzzled what caused it though, the failing builds had `mold` set as linker in my makepkg.conf. For the now working build, I've changed these entries to lld; even though the PKGBUILD disables the buildflags, I had noticed that the flags set in the makepkg.conf still had some impact on some parts of the Kernel build process before but having mold set there wasn't an issue in the past but now it might be.  I've also built a fresh GCC toolchain today.

**Comment by nathanchance** [comment]
If I had to guess, `mold` was being used as the linker for the host tools, which includes `sorttable` (since `mold` cannot be used to link the kernel proper without support for linker scripts). Perhaps `mold` incorrectly links `sorttable`, resulting in this behavior, either due to a `mold` regression or new kernel code exposing a bug in `mold`. Might be worth further investigation on the `mold` side but at any rate, glad to hear it is not an LLVM problem!
