### ISSUE TITLE
kernel requires gcc-4.6

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#27]
As of [commit cafa0010cd51 ("Raise the minimum required gcc version to 4.6")](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=cafa0010cd51fb711fdcb50fc55f394c5f167a0a), the kernel will now refuse to build the kernel with clang, with the following error:

```sh
./include/linux/compiler-gcc.h:14:3: error: Sorry, your compiler is too old - please
      upgrade it.
# error Sorry, your compiler is too old - please upgrade it.
  ^
```

That is because clang defines itself to look like gcc 4.2.1.

I've sent a patch to llvm to upgrade this to 8.2: https://reviews.llvm.org/D51011

We got lucky that this wasn't breaking before.  I think we'll need something more clever in `include/linux/compiler_types.h` for this.

Ideas:
* Don't `#include <linux/compiler-gcc.h>` in `compiler_types.h` if `__clang__` is defined.
* `#undef __GNUC__` and redefine them before including `compiler-gcc.h` if clang.
* ?

**Comment by nathanchance** [comment]
Some quick initial observations:

* Currently, `include/linux/compiler-gcc.h` is included first so that `include/linux/compiler-intel.h` and `include/linux/compiler-clang.h` can override the defaults because all three compilers define `__GNUC__`. Seems like that scheme would need to be reworked if we implement either of the suggested ideas.

* Upgrading Clang's GCC compatibility macros probably isn't a bad starting point but we are going need to check that certain things don't get set in `compiler-gcc.h` that shouldn't be. If Clang has historically appeared as GCC 4.2, upgrading that means there may be version gated definitions that get set that may need to be unset or overwritten in `compiler-clang.h`.

* Kind of interesting that the GCC version is always checked, even for alternative compilers. The Intel compiler must have some workaround for this too I guess. Maybe we just don't do the GCC version check for alternative compilers and assume they set all of their proper definitions in their own compiler files.

If something I said doesn't make sense or is incorrect, please correct me!

**Comment by nathanchance** [comment]
```git
diff --git a/include/linux/compiler-gcc.h b/include/linux/compiler-gcc.h
index 250b9b7cfd60..5e0c8acec5be 100644
--- a/include/linux/compiler-gcc.h
+++ b/include/linux/compiler-gcc.h
@@ -10,9 +10,12 @@
 		     + __GNUC_MINOR__ * 100	\
 		     + __GNUC_PATCHLEVEL__)
 
+/* Don't enforce this check on alternative compilers */
+#if !defined(__clang__) && !defined(__INTEL_COMPILER)
 #if GCC_VERSION < 40600
 # error Sorry, your compiler is too old - please upgrade it.
 #endif
+#endif
 
 /* Optimization barrier */
```

This was my thought for my third point. That check shouldn't be done for alternative compilers; if there is a particular version requirement for a particular compiler, it should be done in the compiler specific `.h` file.

**Comment by dileks** [comment]
@nathanchance That looks fine.

**Comment by nickdesaulniers** [comment]
WIP: https://github.com/ClangBuiltLinux/linux/commit/1f89ae7622c26b8131f42f3a362d6ef41b88a595

**Comment by dileks** [comment]
I was able to build and boot into Linux v4.18.4 with above patch (and some more). My *-dkms (acpi-call, virtualbox and wireguard) modules were also built successfully.

**Comment by nathanchance** [comment]
Accepted upstream: https://github.com/torvalds/linux/commit/815f0ddb346c196018d4d8f8f55c12b83da1de3f

**Comment by nickdesaulniers** [comment]
Thanks for testing @dileks , I'll try to get your tested by on the commit message sooner (wow, it got picked up fast). Thanks for tracking @nathanchance .  You both are super helpful and I appreciate your work.
