### ISSUE TITLE
Building Clang from source: Overriding LINKER_FOR_BUILD

### ISSUE THREAD

**Issue by dileks** [ClangBuiltLinux/linux#358]
I have installed `lld-7` package from Debian/testing AMD64 and tested all possible CMake linker settings:
```
# CMake linker options (here: lld-7, default: ld or alternative: gold)
LINKER_VER="7"
LINKER="lld-$LINKER_VER"
LINKER_CMAKE_OPTS="-DLLVM_USE_LINKER=$LINKER"
```

Looking into the sources this is due to `-fuse-ld=${LLVM_USE_LINKER}`. Allowed seems to be
1. `-fuse-ld=lld` for `ld.lld`
1. `-fuse-ld=gold` for `ld.gold`
1. `-fuse-ld=ld` for `ld.bfd` (defaullt is GNU/ld)

So this line in the wiki is not correct for `ld.bfd`:
```
-DLLVM_USE_LINKER="$(for LD in lld gold bfd; do command -v ld.${LD} &>/dev/null && break; done; echo ${LD})"
```

As I have no `/usr/bin/lld` but `/usr/bin/lld-7` I am able to set it like above.

Using `ld.lld` results in the following configure error (and with all other unallowed linker settings):
```
CMake Error at cmake/modules/HandleLLVMOptions.cmake:203 (message):
  Host compiler does not support '-fuse-ld=ld.lld-7
```

**Comment by dileks** [comment]
Using ld.lld Linker (`-fuse-ld=lld{-7,-8,-9}`) for building is only possible when using clang as CC_FOR_BUILD. Check what `lld` binary you have in `/usr/bin/`.

Nathan says in [1]:
> We'll need to make sure that it is compatible with the way that Clang
> expects arguments to '-fuse-ld=' because it looks like 'ld.' is
> automatically appended.

> https://github.com/llvm/llvm-project/blob/5be3dbdb082ffba4f846e3572ea802d156dd8d34/clang/lib/Driver/ToolChain.cpp#L438-L468

[1] https://lore.kernel.org/r/20190208174553.GA14762@archlinux-ryzen/

**Comment by nathanchance** [comment]
GCC is supposed to support `-fuse-ld=lld`: https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html

I started to look into this yesterday before I had to go to work using our Docker image because all three possible `-fuse-ld=` options work for me on Arch Linux, with both GCC and Clang. I'll try to finish triaging tonight.

**Comment by dileks** [comment]
Hmm, I tried `gcc-8` with `-DLLVM_USE_LINKER=lld-7`. Maybe that needs a symlink `lld-7 -> lld`.

**Comment by dileks** [comment]
Nope.
```
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
...
-- Check for working C compiler: /usr/bin/gcc-8 -- works
-- Check for working CXX compiler: /usr/bin/g++-8 -- works
...
CMake Error at cmake/modules/HandleLLVMOptions.cmake:203 (message):
  Host compiler does not support '-fuse-ld=lld'


```
[configure-log.txt](https://github.com/ClangBuiltLinux/linux/files/2848005/configure-log.txt)

**Comment by dileks** [comment]
Requires in addition `ld.lld -> ld.lld-7` symlink to work.

```
root@iniza:/usr/bin# ll lld* ld.lld*
lrwxrwxrwx 1 root root  8 Feb  9 17:44 ld.lld -> ld.lld-7
lrwxrwxrwx 1 root root 24 Feb  3 17:27 ld.lld-7 -> ../lib/llvm-7/bin/ld.lld
lrwxrwxrwx 1 root root  5 Feb  9 17:37 lld -> lld-7
lrwxrwxrwx 1 root root 21 Feb  3 17:27 lld-7 -> ../lib/llvm-7/bin/lld
lrwxrwxrwx 1 root root 10 Feb  9 17:45 lld-link -> lld-link-7
lrwxrwxrwx 1 root root 26 Feb  3 17:27 lld-link-7 -> ../lib/llvm-7/bin/lld-link
```

**Comment by dileks** [comment]
For the `ld.bfd` case I will do a workaround with a new symlink `bfd -> ld`.

**Comment by nathanchance** [comment]
I've updated that line on the wiki to depend on Clang so that GCC just defaults to the system linker. Additionally, I've made it use the full path to the linker because Clang supports it and it might avoid weird issues in the future.

https://github.com/ClangBuiltLinux/linux/wiki/Building-Clang-from-source/_compare/332e0280eb75cf5fdf8a0bc6deeebc25d05b4a38...b12229fc15c4d8c21196a8da2e84d19913644032

`-DLLVM_USE_LINKER=lld-7` should work with Clang but you may just supply the full path (-DLLVM_USE_LINKER=/usr/lib/llvm-7/bin/ld.lld`). I'm not going to update the wiki's command to look for the different versions of lld. Most people will just install the stable one and if they have a newer one installed, it seems reasonable to make them supply it, as you did.

I'm closing this for now, reopen it if you see fit.

**Comment by dileks** [comment]
Debian has meta-packages for llvm, clang and lld which makes manually symlinking unnessary.
Here for lld:
```
cd /usr/bin/
rm -v ld.lld lld lld-link

apt-get install lld -t testing

LC_ALL=C ll lld* ld.lld*
lrwxrwxrwx 1 root root  8 Dec 26 12:02 ld.lld -> ld.lld-7
lrwxrwxrwx 1 root root 24 Feb  3 17:27 ld.lld-7 -> ../lib/llvm-7/bin/ld.lld
lrwxrwxrwx 1 root root  5 Dec 26 12:02 lld -> lld-7
lrwxrwxrwx 1 root root 21 Feb  3 17:27 lld-7 -> ../lib/llvm-7/bin/lld
lrwxrwxrwx 1 root root 26 Feb  3 17:27 lld-link-7 -> ../lib/llvm-7/bin/lld-link
```

Note: Meta-packages are available for llvm-toolchain version 7 and 8.

**Comment by dileks** [comment]
It is also possible to setup and switch compiler and linker alternatives via `update-alternatives` command.

[1] https://stackoverflow.com/a/28126262
