### ISSUE TITLE
Tracking the status

### ISSUE THREAD

**Issue by skyne98** [ClangBuiltLinux/linux#361]
Hey there!
First of all, thank you for your awesome work and your efforts!

I have to admit, I feel somewhat bad polluting such a well-structured issue list, but I hope that my question is the one that can help some people who are interested in the project.
So, is there a way to track the status of the project? What I mean is maybe a list of kernel versions and some kind of score/list that describes what works and what doesn't. Maybe it can be a good idea to have such status on the project's webpage.

Also, I think that we can use a chance to describe the current status in this issue for newcomers if there isn't a place to find that information 😃. 

Thank you for your time!

**Comment by dileks** [comment]
DISCLAIMER: All below is my personal point of view and experiences.

Thanks for opening this issue.

The first question came to my mind is:
What status are you asking for?

@mkaehlcke Matthias Kaehlcke did post some status report to LKML (see [1]).
You mean something like this?
You find this helpful?
For me Matthias' posting was a trigger to re-entry the development/testing as I was involved in former  lll-project and LLVMLinux projects.

We have a lot of WIPs (Work in Progress) and the interests are widely spread - the same with the people living in different timezones (USA, Europe, etc.). 

We have here people with personal and business interests.
What is your interest?
My current interest is to get Linux-v5.0-rcN build and running with a llvm-toolchain with (experimental) asm-goto support on x86-64 using a kernel-config from Debian.

The project is touching different areas like LLVM tools (I prefer toolchain in this context), the Linux kernel area, CI (continuous integration), testing, documentation, etc.
So, we use the existing infrastructures like mailing list, bug-tracker, etc. in these projects.
Currently, we have no own mailing-list, IRC (there was an issue for this, but currently I do not know the status or there was a decision done), etc.

The good feedback today is, the CBL project is in touch with leading LLVM/Clang and Linux kernel developers and has really good (personal) relationships in the meantime.

@nickdesaulniers Nick Desaulniers is IMHO co-ordinating patiently and insistently CBL and open issues - everywhere (I am 99% sure he has a twin bro or clones around). Hope people agree with this unofficial statement.
@nathanchance Nathan Chancellor setup CI stuff and is mostly first catching breakage in Linux upstream Git and Linux-next and offering patches.
( The list of fellows is too long and incomplete. )

A good first starting point is to check the wiki pages.
There you find build instructions and links to talks, slides, etc. which are extremely helpful.

The ClangBuiltLinux (CBL) project is young and we surely need helping hands.
We are open for improvements.

[1] https://lore.kernel.org/r/20171123001105.GA53228@google.com/

**Comment by skyne98** [comment]
@dileks, thanks for your extensive answer! I will definitely take some time to read the article you referenced.

Regarding what kind of status I am asking about and what my particular interests: I am working on my [small linux distro](https://github.com/skyne98/nebula) based on Alpine (to mitigate some low-level configuration work I don't want to focus on right now) and would have loved to be able to build everything with one compiler. As I am used to Rust and LLVM, this compiler of choice for me is Clang. Sooner or later I will make a move towards building my own version of the kernel for the system and ClangBuiltLinux sounds as if a old dream came true.

Now, to answer the questions more exactly. What I am interested in?
1. Being able to build a kernel (most recent) with Clang without errors
2. Knowing what kind of instabilities I can except after the system boot-up
3. Knowing in which ways the system can be incompatible with existing tools and interfaces
4. Knowing if the work done in this project applies to third-party kernels like Zen Kernel

Maybe it should even be possible to use test suits of some big software packages for testing the stability and correctness of the system.

**Comment by skyne98** [comment]
In general, the issue right now is that there are lots of opened issues, but no way of knowing how ready some of the kernel versions are to be used by the public.

**Comment by dileks** [comment]
Currently, the CI supports Linux v4.19, Linus upstream Git (will get v5.0 final) and Linux-next.

We use several labels to classify issues here: Check for "FIXED" and "BUG" labels as an example.

[1] https://github.com/ClangBuiltLinux/continuous-integration/tree/master/patches
[2] https://github.com/ClangBuiltLinux/linux/labels

**Comment by skyne98** [comment]
So if the kernel version ends up in the CI you can consider it a stable release?

**Comment by nathanchance** [comment]
Hi @skyne98, thanks for checking us out :)

Ultimately, describing the state of the project is a little difficult because it is dependent on a few things:

* **Your kernel version:** We've backported the core Clang support to 4.4 and 4.9. 4.14, 4.19, and 4.20 already had it. [Our continuous integration](https://travis-ci.com/ClangBuiltLinux/continuous-integration/builds/100730092) is building x86_64 and arm64 for all versions, arm32 for 4.9 and up, and ppc64le on 4.14 and up. The caveat with our CI is we are only building the defconfig and no modules (due to Travis' limits). I've been building {x86_64,arm32,arm64} {defconfig,allyesconfig} on linux-next with [a few out of tree patches](https://github.com/nathanchance/patches/tree/master/linux/build-hax) to work around certain build issues, which you may or may not need depending on your architecture and configuration. CI is boot testing with QEMU but I've booted a Raspberry Pi 3 B+ with Clang, @dileks and @nickdesaulniers have booted x86 devices, and the Pixel phones are shipping with Clang so most things should be in a good spot.

* **Your Clang version:** We've fixed bugs in [clang 6.0.1](https://github.com/ClangBuiltLinux/linux/issues?utf8=%E2%9C%93&q=label%3A%22%5BFIXED%5D%5BCLANG%5D+6.0.1%22+), [clang 7](https://github.com/ClangBuiltLinux/linux/issues?utf8=%E2%9C%93&q=label%3A%22%5BFIXED%5D%5BCLANG%5D+7%22+), [clang 8](https://github.com/ClangBuiltLinux/linux/issues?utf8=%E2%9C%93&q=label%3A%22%5BFIXED%5D%5BCLANG%5D+8%22+), and [clang 9](https://github.com/ClangBuiltLinux/linux/issues?utf8=%E2%9C%93&q=label%3A%22%5BFIXED%5D%5BCLANG%5D+9%22+). It's recommended that you get as close as you can to tip of tree (ideally at this point, at least clang 8 since it is at -rc2).

* **Your hardware/kernel configuration:** The kernel as of 4.14 has 23 million lines of code. Even an `allyesconfig` build doesn't get all of that because some kernel config options are mutually exclusive. We're trying to ramp up to running `randconfig` builds but we're not quite there yet. So it is entirely possible there are warnings/errors/panics that we haven't uncovered yet. Please build with your configuration and let us know of any issues that you find.

@nickdesaulniers gave [a good talk](https://www.youtube.com/watch?v=SSWUrWqnSz0) at Linux Plumbers in November outlining what we've done and where we're going. I'm always happy to onboard people as there is a lot of work to be done!

To specifically answer your questions:

> 1. Being able to build a kernel (most recent) with Clang without errors

See above.

> 2. Knowing what kind of instabilities I can except after the system boot-up

In theory, there should be none. Usually, booting is the hardest part. Google is shipping Clang built kernels on their Pixel devices and Chromebooks (the output is from my Pixelbook and Pixel 3 XL).

```
chronos@localhost / $ cat /proc/version
Linux version 4.4.159-15346-gc5e629939ae0 (chrome-bot@swarm-cros-766) (Chromium OS 8.0_pre339409_p20180926-r3 clang version 8.0.0 (/var/cache/chromeos-cache/distfiles/host/egit-src/clang.git 6601c8f525499269dba75f75bbd1ee2671aaa262) (/var/cache/chromeos-cache/distfiles/host/egit-src/llvm.git 36f54002c931a026f490f9fb074c11d91e3487a2) (based on LLVM 8.0.0svn)) #1 SMP PREEMPT Fri Jan 11 09:20:44 PST 2019
chronos@localhost / $ adb shell cat /proc/version
Linux version 4.9.124-geea7439-ab5155929 (android-build@abfarm786) (Android clang version 5.0.1 (https://us3-mirror-android.googlesource.com/toolchain/clang 00e4a5a67eb7d626653c23780ff02367ead74955) (https://us3-mirror-android.googlesource.com/toolchain/llvm ef376ecb7d9c1460216126d102bb32fc5f73800d) (based on LLVM 5.0.1svn)) #0 SMP PREEMPT Fri Nov 30 04:14:33 UTC 2018
```

> 3. Knowing in which ways the system can be incompatible with existing tools and interfaces

I have not heard of any tools that break when building the kernel with Clang. If there are, please let us know.

> 4. Knowing if the work done in this project applies to third-party kernels like Zen Kernel

Well, we're only concerned with mainline and stable. If those third party kernel stay close enough to mainline/stable, they should benefit from this work. If there are any issues with them, please report them.

**Comment by nickdesaulniers** [comment]
> I have to admit, I feel somewhat bad polluting such a well-structured issue list, but I hope that my question is the one that can help some people who are interested in the project.

Welcome, and thank you for taking interest in our work.

> So, is there a way to track the status of the project?

Sorry we don't provide an easy measure.  It's complicated because there's multidimensional support matrix because there's always a question of:
1. what architecture are you targeting? (ie. x86_64, arm64, ppc, etc)
2. what branch of the kernel are you targeting? (ie. mainline, 4.19-LTS, 4.14-LTS, -next, etc)
3. what version of clang are you trying to use? (trunk? clang-7, clang-4, etc)
4. what configs are you trying to use? (some are mutually exclusive, some aren't in the defconfigs, some require others in a complicated chain)

Most people don't understand that complexity and rightly don't want to; so we're doing our best to make things just work out of the box, and provide support for whatever complicated combo of the above someone has or can find.

The list of out of tree patches @dileks linked to (which ideally should be zero) gives a rough estimate of how broken things are out of the box that we know about.

> * Being able to build a kernel (most recent) with Clang without errors

Depends on the above.  Try it and report any bugs if they're not already in this issue tracker.

> * Knowing what kind of instabilities I can except after the system boot-up

Instabilities aren't any of the known issues.  Android and CrOS are already shipping devices with Clang built kernels.  Mostly build issues that get introduced upstream, and burning down the long tail of warnings.

> * Knowing in which ways the system can be incompatible with existing tools and interfaces

I don't think which toolchain you use for you compiler applies.

> * Knowing if the work done in this project applies to third-party kernels like Zen Kernel

I don't know what "Zen kernel" is, so I'm not sure how that applies.

If you'd like to see if it works, by all means please give it a shot.  If you'd like to help contribute, whether it be a way to track things better or even sending patches; we're always looking for new blood.

**Comment by skyne98** [comment]
@nathanchance, @nickdesaulniers, thank you guys a lot for your detailed answers!  I am infinitely glad that the idea is not dead and there are guys out there who have enough skill and knowledge to pull that off.

Nevertheless, as for the Zen Kernel - this is a rather old project going strong to this day which boils down to a set of patches for mainline kernels that reduce input-to-action latency for desktop distributions. Also, it drastically speeds up doing some of the compilation work due to the scheduler behaviour tweaks.

Also, I totally agree that displaying such information is a challange considering how many variables you have to display and present. But we are programmer, if there anyone else who can tackle such challenges better than we can? :smile:

I will try it as soon as I can and if I have any problems I will definitely report!

**Comment by nickdesaulniers** [comment]
Closing the issue for now.  Feel free to keep this thread alive though, or open any new ones.

**Comment by skyne98** [comment]
Sure, thanks!
