### ISSUE TITLE
Clang CFI does not allow indirect function calls to assembly-defined functions

### ISSUE THREAD

**Issue by kees** [ClangBuiltLinux/linux#486]
The current Clang CFI implementation does not allow indirect calls to functions that are defined in .S files. This is most commonly found in assembly routines for crypto functions.

```
asmlinkage void crypto_thing(arg, arg);
...
func = crypto_thing;
...
func(arg, arg);
```

The above will trip CFI (I think since crypto_thing doesn't exist in a .cfi section.) The current work-around is to wrap the function with a static inline C function:

```
asmlinkage void crypto_thing(arg, arg);
static inline crypto_thing_wrapper(arg, arg) {
    return crypto_thing(arg, arg);
}
...
func = crypto_thing_wrapper;
...
func(arg, arg);
```

This isn't viable upstream. Better that Clang be fixed, or we find some marking to trust prototypes declared with asmlinkage.

**Comment by kees** [comment]
Actually, I cannot currently reproduce this locally... I will continue investigation...

**Comment by nickdesaulniers** [comment]
What about declaring `crypto_thing` as:
```c
void __attribute__((__section__(".cfi"))) crypto_thing(arg, arg);
```
? (assuming you literally meant ".cfi section".  cc @samitolvanen

**Comment by samitolvanen** [comment]
Kees means that LLVM doesn't add `crypto_thing` to the CFI jump table, because it doesn't trust the type declared in the function prototype. Note that this only happens when we use `-fsanitize-cfi-cross-dso`, which we need for kernel modules.

I believe there was a good reason for this behavior, but as mentioned, we need a cleaner way to solve the problem upstream. Adding an attribute to LLVM that forces it to trust the function prototype even with cross-DSO CFI might be a viable option.

**Comment by kees** [comment]
Yeah, as Sami mentioned, I can now reproduce this in a small example: I was missing `-fsanitize-cfi-cross-dso`. I've filed the upstream bug:

https://llvm.org/pr41972

**Comment by kees** [comment]
https://reviews.llvm.org/D65629

**Comment by kees** [comment]
Fixed: https://github.com/llvm/llvm-project/commit/0e497d1554a915ace538dc08f03f1661aab8bdf7

**Comment by nickdesaulniers** [comment]
I'm going to let this one ride the clang-10 train.  CFI is an advanced feature based on out of tree patches; there's no rush to get this bugfix into clang-9 IMO.
