### ISSUE TITLE
__must_check is broken w/ clang

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#520]
@Nathan-Huckleberry is investigating/has a patch, and can explain the details. cc @tmroeder

**Comment by Nathan-Huckleberry** [comment]
`Makefile.extrawarn` includes the line
`KBUILD_CFLAGS += -Wno-unused-value`

WUnusedValue is grouped with several other warnings, so they are disabled as well. The hierarchy of warnings that are disabled is listed below.

```
UnusedValue
|-UnusedComparison
  |-warn_unused_comparison ("%select{equality|inequality|relational|three-way}0 comparison result unused")
|-UnusedResult
  |-warn_unused_result ("ignoring return value of function declared with %0 attribute")
|-UnevaluatedExpression
  |-PotentiallyEvaluatedExpression
    |-warn_side_effects_typeid ("expression with side effects will be evaluated despite being used as an operand to 'typeid'")
  |-warn_side_effects_unevaluated_context ("expression with side effects has no effect in an unevaluated context")
|-warn_unused_expr ("expression result unused")
|-warn_unused_voidptr ("expression result unused; should this cast be to 'void'?")
|-warn_unused_container_subscript_expr ("container access result unused - container access should not be used for side effects")
|-warn_unused_call ("ignoring return value of function declared with %0 attribute")
```

Specifically UnusedResult should not be disabled.

I am investigating the warnings that we are ignoring. Depending on how many warnings there are we can remove the `KBUILD_CFLAGS += -Wno-unused-value` line or explicitly re-enable warnings that are useful.

**Comment by tmroeder** [comment]
FWIW, I looked at this recently and found that -Wno-unused-value was only hiding a couple errors when I ran allyesconfig on x86, which you could patch like this:

```
   In file included from net/xdp/xsk.c:28:
   net/xdp/xsk_queue.h:244:2: warning: expression result unused [-Wunused-value]
           WRITE_ONCE(q->ring->producer, q->prod_tail);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   ./include/linux/compiler.h:283:6: note: expanded from macro 'WRITE_ONCE'
           __u.__val;                                      \
           ~~~ ^~~~~
   diff --cc net/ipv4/fib_trie.c
   index d97286eb08d01,d97286eb08d01..49144d21e82d9
   --- a/net/ipv4/fib_trie.c
   +++ b/net/ipv4/fib_trie.c
   @@@ -349,12 -349,12 +349,12 @@@ static struct tnode *tnode_alloc(int bi

     static inline void empty_child_inc(struct key_vector *n)
     {
   --      ++tn_info(n)->empty_children ? : ++tn_info(n)->full_children;
   ++      (void)(++tn_info(n)->empty_children ? : ++tn_info(n)->full_children);
     }

     static inline void empty_child_dec(struct key_vector *n)
     {
   --      tn_info(n)->empty_children-- ? : tn_info(n)->full_children--;
   ++      (void)(tn_info(n)->empty_children-- ? : tn_info(n)->full_children--);
     }

     static struct key_vector *leaf_new(t_key key, struct fib_alias *fa)
```

**Comment by nickdesaulniers** [comment]
yeah those statements gave me a laugh. @Nathan-Huckleberry filed: https://llvm.org/pr42239

**Comment by nhukc** [comment]
Patch submitted: https://lore.kernel.org/r/20190617172829.164520-1-nhuck@google.com/

**Comment by nathanchance** [comment]
I stumbled across https://crbug.com/974884 and I am little bit confused after looking into it further.

How does `-Wunused-value` control `-Wunused-variable` and `-Wunused-const-variable`? According to [the documentation](https://clang.llvm.org/docs/DiagnosticsReference.html#wunused-value), `-Wunused-value` controls `-Wunevaluated-expression`, `-Wunused-comparison`, and `-Wunused-result` and [the source](https://github.com/llvm/llvm-project/blob/83338b1059aaf3393f52da1138425774c3514cdf/clang/include/clang/Basic/DiagnosticGroups.td#L608-L612) backs this up.

Furthermore, `-Wunused-variable` is enabled by default with `-Wall` and I don't see either warning get disabled if I disable `-Wunused-value`: https://godbolt.org/z/_558cE

So how is `-Wunused-const-variable` getting enabled here (not that it is a bad thing, I just want to see where things are breaking down since they should be disabled after 0a5f41767444cc3b4fc5573921ab914b4f78baaa) and why is `-Wunused-variable` not showing up for CrOS? This is purely tangential to this issue and I'll probably post further findings on that bug if it is appropriate.

**Comment by nickdesaulniers** [comment]
mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4df607cc6fe8e46b258ff2a53d0a60ca3008ffc7
