### ISSUE TITLE
stack state mismatch in drivers//hwmon/smsc47m1.o

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#535]
reported via 0day bot: https://groups.google.com/forum/#!topic/clang-built-linux/accdubaTcYo

> If you fix the issue, kindly add following tag 
> Reported-by: kbuild test robot <lkp@intel.com> 

looks like this was found in -next for x86_64. (so adding the -next label, but I assume this is a bug in LLVM possibly related to asm goto)

**Comment by nathanchance** [comment]
I think this has been reported and fixed already.

https://lore.kernel.org/lkml/badd630c-4bf9-1694-11ec-cbfd13964516@roeck-us.net/

https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=6d7c58656487d2265fdb75b90358d311079a84f7

Sorry, I mentally replied by archiving the email, rather than actually replying...
