### ISSUE TITLE
Further -Wundef cases

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#570]
Joe Perches pointed out there may be further `-Wundef` warnings lurking.

https://lore.kernel.org/lkml/67f6cd269684c9aa8463ff4812c3b4605e6739c3.camel@perches.com/

I will need to look into whether or not these are real config variables (that may be undefined) or ones that are created with a `#define` directive in a C file, which may always be defined and if they can ever be triggered.

**Comment by nickdesaulniers** [comment]
Looking at one example, `kernel/futex.c:#if CONFIG_BASE_SMALL`: https://github.com/ClangBuiltLinux/linux/blob/83d09ad4b950651a95d37697f1493c00d888d0db/kernel/futex.c#L4045-L4049

It seems that this is always defined; for defconfigs I see:
```sh
$ grep -n BASE_SMALL .config           
751:CONFIG_BASE_SMALL=0
```
so that case is fine. See it's kconfig: https://github.com/ClangBuiltLinux/linux/blob/83d09ad4b950651a95d37697f1493c00d888d0db/init/Kconfig#L2043-L2046.

So ints are probably fine. Here's the latest list on mainline @ 16fc44d6387e260f4932e9248b985837324705d8
```sh
$ git grep -nP '^\s*#\s*if\s+CONFIG_[A-Z0-9_]+\s*$' *
arch/microblaze/include/asm/exceptions.h:20:#if CONFIG_XILINX_MICROBLAZE0_USE_MSR_INSTR
arch/microblaze/include/asm/hash.h:34:#if CONFIG_XILINX_MICROBLAZE0_USE_BARREL
arch/microblaze/include/asm/irqflags.h:12:#if CONFIG_XILINX_MICROBLAZE0_USE_MSR_INSTR
arch/microblaze/kernel/entry.S:52:#if CONFIG_XILINX_MICROBLAZE0_USE_MSR_INSTR
arch/microblaze/kernel/entry.S:967:#if CONFIG_MANUAL_RESET_VECTOR
arch/microblaze/kernel/setup.c:149:#if CONFIG_XILINX_MICROBLAZE0_USE_MSR_INSTR
arch/powerpc/platforms/powernv/pci.c:714:#if CONFIG_EEH
arch/x86/boot/compressed/misc.c:175:#if CONFIG_X86_NEED_RELOCS
arch/x86/boot/compressed/misc.h:82:#if CONFIG_RANDOMIZE_BASE
drivers/gpu/drm/i915/gt/sysfs_engines.c:450:#if CONFIG_DRM_I915_HEARTBEAT_INTERVAL
drivers/gpu/drm/i915/gt/sysfs_engines.c:492:#if CONFIG_DRM_I915_HEARTBEAT_INTERVAL
kernel/futex.c:4016:#if CONFIG_BASE_SMALL
```

arch/microblaze/Kconfig.platform:
 43 config XILINX_MICROBLAZE0_USE_MSR_INSTR                                                                                                                                     
 44   int "USE_MSR_INSTR range (0:1)"                                                                                                                                           
 45   default 0

arch/microblaze/Kconfig:
169 config MANUAL_RESET_VECTOR                                                                                                                                                  
170   hex "Microblaze reset vector address setup"                                                                                                                               
171   default "0x0"

arch/powerpc/platforms/Kconfig
166 config EEH                                                                                                                                                                  
167   bool

arch/x86/Kconfig
2164 config X86_NEED_RELOCS                                                                                                                                                     
2165   def_bool y

arch/x86/Kconfig
2128 config RANDOMIZE_BASE                                                                                                                                                      
2129   bool "Randomize the address of the kernel image (KASLR)"

drivers/gpu/drm/i915/Kconfig.profile
 28   int "Interval between heartbeat pulses (ms)"                                                                                                                              
 29   default 2500 # milliseconds 

===

So only X86_NEED_RELOCS, RANDOMIZE_BASE, and EEH are boolean configs. I wonder if I can repro them with `allnoconfig`? Nope. It looks like the top level Makefile sets -Wundef with -Wall, but #618 in arch/x86/boot/compressed/Makefile resets that and doesn't re-set it. If we add `-Wundef`, and disable RANDOMIZE_BASE, it does repro. Same for X86_NEED_RELOCS.
```
arch/x86/boot/compressed/misc.h:82:5: warning: 'CONFIG_RANDOMIZE_BASE' is not defined, evaluates to 0 [-Wundef]
#if CONFIG_RANDOMIZE_BASE
    ^
arch/x86/boot/compressed/misc.c:175:5: warning: 'CONFIG_X86_NEED_RELOCS' is not defined, evaluates to 0 [-Wundef]
#if CONFIG_X86_NEED_RELOCS
    ^
```
I will send a patch.

**Comment by nickdesaulniers** [comment]
Sent https://lore.kernel.org/lkml/20210422190450.3903999-1-ndesaulniers@google.com/T/#u for x86. Will post a fix for CONFIG_EEH, too.

**Comment by nickdesaulniers** [comment]
CONFIG_EEH can't be disabled for this file, so it's not possible to get an error out of is.

**Comment by nickdesaulniers** [comment]
But the else case can probably be deleted.

Menuconfig for CONFIG_EEH:
  x   Depends on: (PPC_POWERNV [=y] || PPC_PSERIES [=n]) && PCI [=y])

Sent: https://lore.kernel.org/linuxppc-dev/20210422195405.4053917-1-ndesaulniers@google.com/

**Comment by nickdesaulniers** [comment]
the x86 patch landed as a554e740b66a83c7560b30e6b50bece37555ced3. I've pinged the ppc one.

**Comment by nickdesaulniers** [comment]
v2 of ppc patch: https://lore.kernel.org/lkml/20210518204044.2390064-1-ndesaulniers@google.com/

**Comment by nickdesaulniers** [comment]
ppc patch accepted: https://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux.git/commit/?id=73e6e4e01134c9ee97433ad1f470c71b0748b08f

**Comment by nickdesaulniers** [comment]
73e6e4e01134c9ee97433ad1f470c71b0748b08f
