### ISSUE TITLE
-Wempty-body and -Wparentheses-equality in drivers/isdn/hisax/*

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#66]
```
  CC      drivers/isdn/hisax/hfc_pci.o
drivers/isdn/hisax/hfc_pci.c:131:34: warning: if statement has empty body
      [-Wempty-body]
        if (Read_hfc(cs, HFCPCI_INT_S1));
                                        ^
drivers/isdn/hisax/hfc_pci.c:131:34: note: put the semicolon on a separate line to
      silence this warning
drivers/isdn/hisax/hfc_pci.c:161:34: warning: if statement has empty body
drivers/isdn/hisax/hfc_pci.c:1540:38: warning: if statement has empty body
drivers/isdn/hisax/hfc_sx.c:384:33: warning: if statement has empty body
drivers/isdn/hisax/hfc_sx.c:414:33: warning: if statement has empty body
drivers/isdn/hisax/hfc_sx.c:1291:37: warning: if statement has empty body

drivers/isdn/hisax/w6692.c:627:30: warning: equality comparison with extraneous
      parentheses [-Wparentheses-equality]
```
Can probably be fixed together.

**Comment by nathanchance** [comment]
Patch sent for the parentheses equality: https://lore.kernel.org/lkml/20180920040523.21671-1-natechancellor@gmail.com/

I think `-Wempty-body` is just becoming noise. Clang is complaining about statements like `if (Read_hfc(cs, HFCPCI_INT_S1));`, which is just making sure that `Read_hfc` runs and doesn't require a variable for the return value (otherwise GCC complains, I tried). I could move the semicolon to the next line like it asks but looks less elegant in my opinion (although in this particular case, this driver looks awful aside from these statements).

I personally think it should just be hidden behind `W=1` like suggested in #42. I guess this is trying to fix bugs of the following style:

```C
if (condition);
        statement
```

but I'd argue there are very few of those cases in the kernel since GCC's `-Wmisleading-indentation` warning already catches those.

**Comment by nathanchance** [comment]
The `-Wparenthesis-equality` fix is now in -next: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=faa08325b429dabb7f55ff65a9a238e126537a49

**Comment by nathanchance** [comment]
Masahiro's response to disabling the warning: https://lore.kernel.org/lkml/CAK7LNATO+L4-0SpuWrCnYEUVbxmcQkjOQvMB6PEsFv1b-heJOA@mail.gmail.com/

Patch sent: https://lore.kernel.org/lkml/20181017180657.9410-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch v2: https://lore.kernel.org/lkml/20181018034935.16819-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch v3: https://lore.kernel.org/lkml/20181019011103.32087-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git/commit/?id=a1930a9877d66e9333fc1b1ceeec1ab54591a91f

**Comment by nathanchance** [comment]
Both patches merged into mainline.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=faa08325b429dabb7f55ff65a9a238e126537a49

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a1930a9877d66e9333fc1b1ceeec1ab54591a91f
