### ISSUE TITLE
ERROR: "__aeabi_uldivmod" [net/core/pktgen.ko] undefined!

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#848]
Reported-by: ci_notify@linaro.org
```
00:04:26 ERROR: "__aeabi_uldivmod" [net/core/pktgen.ko] undefined!

```
on a build of mainline allmodconfig.

**Comment by nathanchance** [comment]
Sounds like the problematic change is going to get reverted because the author was notified of the issue and never fixed it:

https://lore.kernel.org/netdev/20200127.135104.544840622177386473.davem@davemloft.net/

https://lore.kernel.org/netdev/20200120.100345.1624559406391044919.davem@davemloft.net/

https://lore.kernel.org/netdev/20200126.205613.19167395629782356.davem@davemloft.net/

**Comment by nathanchance** [comment]
Fixed by having the patch dropped.
