### ISSUE TITLE
Time of clang compiling Linux is double than gcc

### ISSUE THREAD

**Issue by 12101111** [ClangBuiltLinux/linux#853]
Compile Linux 5.5.1 using same config.
Disk: tmpfs on 16GB dual channel DDR4 2133 MHz
CPU: 6300HQ (4x skylake @ 3.0 GHz)
1. Test on Gentoo Linux, measure with zsh builtin `time` command
clang 9.0.1 (build with lto): 
```
2734.22s user
178.77s system
392% cpu
12:22.93 total
```
gcc 9.2.0(build with lto and pgo): 
```
1305.98s user
147.62s system
387% cpu 
6:15.15 total
```
Because Gentoo ebuild of llvm and clang don't support pgo, I decide to run another test without optimized compiler.
2. Test on Alpine Linux (chroot),  measure with busybox builtin `time` command
clang 9.0.1:
```
real    20m 25.24s
user    1h 17m 41s
sys     2m 39.52s
```
gcc 9.2.0:
```
real    8m 23.31s
user    30m 29.01s
sys     2m 9.93s
```

**Comment by nathanchance** [comment]
Are these versions of clang that you have built yourself? I have never seen this on my machines (in fact, I’m doing a set of benchmarks right now around GCC vs. Clang when compiling the kernel). The only reason I could think that this is happening is because you have assertions enabled or you are running a debug build.

A set of benchmarks that I did with LLVM 9 vs GCC 9: https://gist.github.com/nathanchance/7bc40942ac0a86490e692b63345e6f6a

**Comment by 12101111** [comment]
I took 8 hours to bootstrap LLVM 10 with full lto and pgo, the performance is impressive:

| toolchains                   | real        | user        | sys        |
| ---------------------------- | ----------- | ----------- | ---------- |
| clang 9.0.1(Gentoo thin LTO) | 12m 22.93s  | 45m 34.22s  | 2m 58.77s  |
| gcc 9.2.0(Gentoo PGO & LTO)  | 6m 15.15s   | 21m 45.98s  | 2m 27.62s  |
| gcc 9.2.0(Alpine)            | 8m 23.31s   | 30m 29.01s  | 2m 9.93s   |
| clang 9.0.1(Alpine)          | 20m 25.24s  | 1h 17m 41s  | 2m 39.52s  |
| clang 10.0 stage1            | 10m 29.749s | 38m 53.080s | 2m 20.083s |
| clang 10.0 (PGO & full LTO)  | 7m 58.829s  | 28m 51.638s | 2m 14.830s |

Looks like a huge performance boost comes from PGO
