### ISSUE TITLE
make CC=clang tools/perf isn't hermetic

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#901]
```sh
$ make CC=clang tools/perf
$ llvm-readelf --string-dump=.comment ./tools/perf/perf
String dump of section '.comment':
[     0] GCC: (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0
[    2b] clang version 10.0.0 (https://github.com/llvm/llvm-project.git ae09dd86a9b7f43543baa92d27c9382099691088)
[    94] GCC: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
```
*yikes* for one GCC, *double yikes* for two.

**Comment by ihalip** [comment]
Looks like the object files inside `tools/perf/pm-events` are built with $HOSTCC.
Using `make CC=clang-11 HOSTCC=clang-11`, there don't seem to be any object files built with GCC any longer:
```
$ find tools/perf/ -name \*.o -exec sh -c 'readelf --string-dump=.comment {} 2>&1 | grep GCC' \;
$ 
```

However, some host libraries (maybe some of which are static?) get linked into the perf binary. I think that's why you see those.

**Comment by nickdesaulniers** [comment]
HOSTCC it is then; makes sense for `perf` which is meant to be run on the host, not necessarily the target (when cross compiling)
