### ISSUE TITLE
-Wunused-function in include/uapi/linux/usb/raw_gadget.h

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#934]
`Reported-by: kernelci.org bot <bot@kernelci.org>`
```
    ./usr/include/linux/usb/raw_gadget.h:69:12: warning: unused function 'usb_raw_io_flags_valid' [-Wunused-function]
    ./usr/include/linux/usb/raw_gadget.h:74:12: warning: unused function 'usb_raw_io_flags_zero' [-Wunused-function]
```

I'm not sure why these would be unused; I don't see any `CONFIG` `#ifdef`'ery.

These are in include/uapi/linux/usb/raw_gadget.h, and should probably be marked `inline`. Seems to be from f2c2e717642c6? cc @xairy

**Comment by nathanchance** [comment]
This comes from CONFIG_UAPI_HEADER_TEST, which tests that the UAPI headers are self-contained; it does this by compiling them as standalone translation units so because `usb_raw_io_flags_valid` and `usb_raw_io_flags_zero` are not used in the file, clang warns.

Not sure if marking `inline` will do anything since I don't think that UAPI uses `compiler.h`.

**Comment by xairy** [comment]
Marking them `inline` sounds good, if this helps. I'll do that in the next version of the patchset.

**Comment by xairy** [comment]
Mailed a fix in a separate patch instead: https://patchwork.kernel.org/patch/11443077/

**Comment by nathanchance** [comment]
Fixed: https://git.kernel.org/next/linux-next/c/956ae8df7fed0a2acc7ae934f24493eaeb031f62
