### ISSUE TITLE
deprecated since v7, use 'dsb'

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#956]
armv7 defconfig linux-next AS=clang
```
arch/arm/mm/flush.c:46:3: warning: deprecated since v7, use 'dsb' [-Winline-asm]
        "       mcr     p15, 0, %2, c7, c10, 4"
         ^
<inline asm>:2:2: note: instantiated into assembly here
        mcr     p15, 0, r7, c7, c10, 4
        ^
arch/arm/mach-at91/pm.c:394:17: warning: deprecated since v7, use 'dsb' [-Winline-asm]
                ".align    5\n\t"
                              ^
```

**Comment by nickdesaulniers** [comment]
oh, I have https://lore.kernel.org/lkml/a651d5eaf312c771c9d2e0160ddd905550bbd4e3.1585507235.git.stefan@agner.ch/ applied, so that may be required to reproduce

**Comment by nickdesaulniers** [comment]
cc @agners

**Comment by agners** [comment]
@nickdesaulniers yeah this is a warning which is there since quite a while. It is not related to the patch above. We could get rid of them using `-no-deprecated-warn`, but I think we could improve the code on kernel side to get rid of them. This wasn't high on my priority list so far since I still have build errors with `AS=clang`...

Issue #306 is somewhat related to that.

**Comment by nickdesaulniers** [comment]
It looks like https://lore.kernel.org/lkml/a651d5eaf312c771c9d2e0160ddd905550bbd4e3.1585507235.git.stefan@agner.ch/ never got submitted?

**Comment by nickdesaulniers** [comment]
I suspect https://reviews.llvm.org/rG1d51c699b9e2ebc5bcfdbe85c74cc871426333d4 fixes this?

**Comment by arndb** [comment]
It would be nice to have a way to warn about these instructions if anyone ever tries to build a kernel for ARMv6+v7+v8, since it is an actual bug in this case and will not work on an ARMv8 processor. The kernel currently does not really support ARMv8 configurations, so one would first have to add that in the kernel, but then also have a way to tell the assembler which combination of architectures we target, rather than just the minimum architecture.

**Comment by nickdesaulniers** [comment]
> I suspect https://reviews.llvm.org/rG1d51c699b9e2ebc5bcfdbe85c74cc871426333d4 fixes this?

Yes, dup of #1195
