### ISSUE TITLE
unknown pseudo-op: `.attribute`

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#967]
via: https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/jobs/311246235
```
/tmp/empty-955e67.s: Assembler messages:
/tmp/empty-955e67.s:2: Error: unknown pseudo-op: `.attribute'
/tmp/empty-955e67.s:3: Error: unknown pseudo-op: `.attribute'
```

**Comment by nathanchance** [comment]
`+ riscv64-linux-gnu-as --version`

I'll switch us over to the integrated assembler: https://github.com/nathanchance/continuous-integration/commit/6d1cdb4f79e34335a979c52406d3fb0594bff8dc

**Comment by MaskRay** [comment]
RISC-V attribute section was committed yesterday https://reviews.llvm.org/D74023

**Comment by nathanchance** [comment]
I assume a newer version of binutils supports that but our Docker image is stuck with 2.31.1 since that is the latest version from Debian stable. Could jump on unstable to get 2.34 but I think I'd rather just turn on the integrated assembler and use older binutils until we are absolutely forced to jump forward.

As it stands, I think RISCV only needs binutils for `ld.bfd` due to a problem with `ld.lld` (https://github.com/ClangBuiltLinux/linux/issues/805). It should use all of the other tools no problem.
