### ISSUE TITLE
A large number of unmerged sections with LTO

### ISSUE THREAD

**Issue by samitolvanen** [ClangBuiltLinux/linux#969]
Looking at a kernel and modules built with LTO, I'm seeing a huge number of data sections that are not merged by the usual linker script rules:
```
.bss..compoundliteral*
.data..Lanon*
.data..compoundliteral*
.rodata..Lswitch*
.rodata..L__const*
.rodata..L.str*
```
For example, with arm64 defconfig + LTO + CFI:
```
$ aarch64-linux-gnu-readelf --sections --wide vmlinux | grep -c '\.data\.\.L'
10044
$ for i in `find . -name \*.ko`; do aarch64-linux-gnu-readelf --sections --wide $i; \
done | grep -c 'data\.\.L'
16662
```
As each section increases the size of the binaries we're shipping, merging these would make sense.

@MaskRay @nickdesaulniers  Is there documentation what these sections are? Do you expect any issues if we choose to merge them to .bss/data/rodata?

**Comment by gwelymernans** [comment]
We're seeing similar for PPC builds with `.data..compoundliteral*` sections.

**Comment by jesec** [comment]
Related issue: https://github.com/ClangBuiltLinux/linux/issues/958

It seems that commit https://github.com/aosp-mirror/kernel_common/commit/23cbf245be53692164a95db68466d36c67eaca49 failed to solve the problem on android-4.19 branch. 

```
 [~/k/out] [G lineage-17.1 8485f6d] [ANDROID: kbuild: merge more sections with LTO]
 Θ aarch64-linux-gnu-readelf --sections --wide vmlinux | grep -c compoundliteral
4526

 [~/k/out] [G lineage-17.1 8485f6d] [ANDROID: kbuild: merge more sections with LTO]
 Θ aarch64-linux-gnu-readelf --sections --wide vmlinux | grep -c L_MergedGlobals
106
```

Similar to what was done in https://github.com/aosp-mirror/kernel_common/commit/5d8fc94e6f897323e10912667987f6a91b092f0f for android-4.14 branch, I need to:
```
diff --git a/include/asm-generic/vmlinux.lds.h b/include/asm-generic/vmlinux.lds.h
index 07b709ab1ff6..2915fa0fbd79 100644
--- a/include/asm-generic/vmlinux.lds.h
+++ b/include/asm-generic/vmlinux.lds.h
@@ -69,10 +69,10 @@
 #if defined(CONFIG_LD_DEAD_CODE_DATA_ELIMINATION) || defined(CONFIG_LTO_CLANG)
 #define TEXT_MAIN .text .text.[0-9a-zA-Z_]*
 #define TEXT_CFI_MAIN .text.[0-9a-zA-Z_]*.cfi
-#define DATA_MAIN .data .data.[0-9a-zA-Z_]* .data..LPBX*
+#define DATA_MAIN .data .data.[0-9a-zA-Z_]* .data..LPBX* .data..compoundliteral* .data..L_MergedGlobals*
 #define SDATA_MAIN .sdata .sdata.[0-9a-zA-Z_]*
 #define RODATA_MAIN .rodata .rodata.[0-9a-zA-Z_]*
-#define BSS_MAIN .bss .bss.[0-9a-zA-Z_]*
+#define BSS_MAIN .bss .bss.[0-9a-zA-Z_]* .bss..compoundliteral* .bss..L_MergedGlobals*
 #define SBSS_MAIN .sbss .sbss.[0-9a-zA-Z_]*
 #else
 #define TEXT_MAIN .text
```

**Comment by nickdesaulniers** [comment]
The compound literal sections are created because compound literals have either static or automatic storage lifetime; for static literals that use compound literals to intialize members, these "anonymous" static objects are created. They are just syntactic sugar.
https://gcc.gnu.org/onlinedocs/gcc/Compound-Literals.html

Because `-flto{=thin}` implies `-fdata-sections`, a section is created for each instance of this global.  Comparing the disassemblies between not-merging and merging, nothing stands out to me as being wrong, so I'm not convinced that merging them is not safe.  For that reason, I'm closing this bug, but let's reopen if we find evidence later that refutes that.

I'm not sure precisely what Lanon or L__const are, but Lswitch and Lstr are likely jump tables and non-global string literals.  Either way, you can disassemble just a section via `llvm-objdump -drj <section name> vmlinux` (`-j .data..Lanonfoo`) to see what symbol/identifier created those (unless they were generated like the jump tables).

https://android-review.googlesource.com/c/kernel/common/+/1331742 is only meant to affect modules, ie. *.ko files.  https://lore.kernel.org/kernel-hardening/20200624203200.78870-3-samitolvanen@google.com/ adds those to the vmlinux linker script.
